test/Microsoft.OpenApi.Tests/Models/OpenApiComponentsTests.cs
- Change one of the unit tests in Components to have reference in the inner level to verify that serialization of references work correctly in the Components (in the inner level) - most common cases.
- Top-level reference in Components is still not serialized correctly per #157.
This is NOT a fix to #157, but a test that 
1. Helps us understand the current behavior
2. Can be used to verify #157 once a fix is written.
=> Fix unit test to confirm that reference issue in Component is contained to only top-level reference

src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, src/Microsoft.OpenApi.Workbench/MainModel.cs, src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/OpenApiSerializerSettings.cs, src/Microsoft.OpenApi/OpenApiSpecVersion.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiComponentsTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiContactTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiEncodingTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiExternalDocsTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiInfoTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiLicenseTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiMediaTypeTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOAuthFlowTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOAuthFlowsTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiReferenceTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiResponseTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSecurityRequirementTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSecuritySchemeTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiServerTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiServerVariableTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiXmlTests.cs
- Output as V3.0.1
- Recognize any V3.0.X when deserializing
Fix #159
=> Support v3.0.1

src/Microsoft.OpenApi/Models/OpenApiComponents.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterExtensions.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiComponentsTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs
Fixes #157 
For each component (in Components in V3 or in Definitions/Parameters/etc. in V2), use the following serialization paradigm:
- If we don't see any reference, write full object.
- If we see a Reference to itself, write the full object without $ref.
- If we see a Reference to another object, always write as $ref
This is done by making "a Reference to itself" a special case (i.e. using SerializeAsVXWithoutReference). The rest of the logic is handled in SerializeAsVX.
=> Serialize reference in top-level component properly

src/Microsoft.OpenApi.Readers/Exceptions/OpenApiReaderException.cs, src/Microsoft.OpenApi.Readers/Exceptions/OpenApiUnsupportedSpecVersionException.cs, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/OpenApiReaderTests/Samples/unsupported.v1.yaml, test/Microsoft.OpenApi.Readers.Tests/OpenApiReaderTests/UnsupportedSpecVersionTests.cs
See https://github.com/Microsoft/OpenAPI.NET/issues/177 for context. 
I've introduced a fundamental exception type of `OpenApiReaderException` and throw an `OpenApiUnsupportedSpecVersionException` when we encounter an unrecognized version. The former exception type is meant to be the base type for any more specific exception types to come in future.
Test added with version 1.0.0, which I assume we'll never support, so the test should be robust in future versions of OpenAPI spec.
=> [Fix 177]: Throw exception when spec version is not recognized by reader

src/Microsoft.OpenApi.Readers/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, src/Microsoft.OpenApi/Models/OpenApiParameter.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/basicOperation.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/operationWithBody.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/operationWithFormData.yaml, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs
- Fix the serialization and deserialization logic for V2 formData and body parameter.
- V2 operation deserialization now respects the `consumes` property.
- Unit tests verify that serializing, deserializing, and re-deserializing all work as expected.
Fix #178 
Fix #179
=> Fix formData/body parameter and consumes handling

src/Microsoft.OpenApi/Validations/OpenApiValidator.cs, src/Microsoft.OpenApi/Validations/ValidationRuleSet.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiValidatorTests.cs, test/Microsoft.OpenApi.Tests/Validations/ValidationRuleSetTests.cs
Re-enable the default rule count test case (disabled in #176)
The problem was this:
ValidateCustomExtension test calls ValidationRuleSet.DefaultRuleSet and makes changes to it directly. Since the DefaultRuleSet is cached, the underlying private `_defaultRuleSet` is actually modified.
The reason we did not see the issue locally might be that the order of local test run and the order on AppVeyor are different. We see the issue only if the "Count" test is run after the custom extension test.
=> Re-enable the default rule count test case

src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterAnyExtensionsTests.cs
The purpose of this PR is make sure that OpenApiFloat, OpenApiDouble, and OpenApiLong are supported in the default serializers (which inherits from OpenApiWriterBase).
Fixes issue https://github.com/Microsoft/OpenAPI.NET/issues/199
Some questsions:
1. I first added tests for long, float and double. Float and double tests failed expectedly, but the long tests somehow passed, even though no overloads or cases for long had yet been added. I dug around but could not find the reason why this is happening. Is the runtime implicitly casting the longs as ints? The tests still pass using long.MaxValue, which should rule out that possibility. I still added an overload and a case for long, for consistency. Please comment.
2. Is the tests I wrote for double and float satisfactory? Do we need to take …
=> Support all numeric IOpenApiAny types in OpenApiWriterBase

src/Microsoft.OpenApi/Models/OpenApiSchema.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs
V2 serialization code changes to not allow a child property of a schema to be readonly if its inlcuded in the list of required properties of parent schema, to comply with V2 spec.
=> Do not mark require property as read only

src/Microsoft.OpenApi/Validations/Rules/OpenApiResponsesRules.cs, test/Microsoft.OpenApi.Tests/Validations/ValidationRuleSetTests.cs
=> Fix Responses rule

src/Microsoft.OpenApi/Models/OpenApiResponse.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiResponseTests.cs
Issue #217:
The current writer logic to write the example in content of response is wrong. it will throw exception.
This PR tries to fix it.
=> modify to writer the any example for response in v2

src/Microsoft.OpenApi.Readers/V3/OpenApiParameterDeserializer.cs, src/Microsoft.OpenApi/Models/OpenApiParameter.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs
=> Changed parameter examples to be dictionary instead of list and fixed ref resolution

src/Microsoft.OpenApi.Readers/Services/OpenApiReferenceResolver.cs, src/Microsoft.OpenApi/Services/OpenApiVisitorBase.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiDocument/securedApi.yaml, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiOperation/securedOperation.yaml
=> Fixed security requirement resolution 

src/Microsoft.OpenApi/Models/OpenApiOperation.cs
Fix a bug in OpenApiOperation. 
The sub function call should target the correct version. See detail in the changed files. 
Thanks.
=> fix a bug in OpenApiOperation

Microsoft.OpenApi.sln, src/Microsoft.OpenApi.Readers/OpenApiReaderSettings.cs, src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, src/Microsoft.OpenApi.Readers/Services/OpenApiReferenceResolver.cs, src/Microsoft.OpenApi.Workbench/MainModel.cs, src/Microsoft.OpenApi.Workbench/MainWindow.xaml, src/Microsoft.OpenApi.Workbench/MainWindow.xaml.cs, src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj, src/Microsoft.OpenApi.Workbench/StatsVisitor.cs, src/Microsoft.OpenApi/Extensions/OpenApiElementExtensions.cs, src/Microsoft.OpenApi/Services/OpenApiVisitorBase.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, src/Microsoft.OpenApi/Validations/OpenApiValidator.cs, src/Microsoft.OpenApi/Validations/ValidationRuleSet.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiValidatorTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiComponentsValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiContactValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiExternalDocsValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiInfoValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiLicenseValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiOAuthFlowValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiReferenceValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiResponseValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiServerValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiTagValidationTests.cs
The primary problem resolved in this PR is the walker, which is used for both reference resolution and validation, was walking objects multiple times when they were $ref'd.  This has been resolved in the OpenApiWalker by adding a guard that does not walk the object if it has a non-null Reference and we are currently not walking through the Components section.
For the large 30MB, million line MS Graph OpenAPI, the time has gone from > 20mins, to ~ 10 secs on my Surface Pro 4.
I also added some statistics to the workbench to get an overview of the parsed file.  e.g. for the Graph API file it produces:
Path Items: 6783
Operations: 10609
Parameters: 23392
Request Bodies: 3815
Responses: 10609
Links: 132
Callbacks: 0
Schemas: 336995
Also updated Workbench to allow taking input from a file.
=> Performance enhancements to validation and reference resolution

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
Fix #149 
Add Microsoft logo as NuGet package icon
I'm using the logo from http://go.microsoft.com/fwlink/?LinkID=288890, which is what other existing Microsoft packages from Azure are using:
https://www.nuget.org/packages/Microsoft.ServiceFabric.FabricTransport.Internal/
https://www.nuget.org/packages/Microsoft.WindowsAzure.Management/
=> Add NuGet package icon

src/Microsoft.OpenApi.Readers/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterExtensions.cs, test/Microsoft.OpenApi.Readers.Tests/ReferenceService/TryLoadReferenceV2Tests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiPathItemTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs
=> Changed OpenApiSchema.Required to ISet

src/Microsoft.OpenApi.Readers/ParseNodes/ValueNode.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiAnyTests.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterAnyExtensionsTests.cs
=> Fix for writing DateTimeOffset values

README.md
Updating the README.md to link to the new C# comment processor.
=> Linking back the new C# annotations processor.

src/Microsoft.OpenApi.Readers/V2/OpenApiHeaderDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiParameterDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiParameterTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiParameter/headerParameter.yaml
Several fields were not supported and some were supported that don't exist in V2.  I also re-ordered the parsing code to match the spec order.
=> Fix header deserialization in V2 documents

src/Microsoft.OpenApi.Readers/V3/OpenApiExampleDeserializer.cs
Added missing property in Examples Object.  This is a quick fix for the Docs team.  In 1.1 we will add support for reading external files.
=> Added parsing externalValue to Examples Object

src/Microsoft.OpenApi.Readers/Exceptions/OpenApiUnsupportedSpecVersionException.cs, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi.Readers/OpenApiReaderSettings.cs, src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiResponseDeserializer.cs, src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiResponse.cs, src/Microsoft.OpenApi/Writers/IOpenApiWriter.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, src/Microsoft.OpenApi/Writers/SpecialCharacterStringExtensions.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiServerTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiValidatorTests.cs, test/Microsoft.OpenApi.Tests/Walkers/WalkerLocationTests.cs
- Merged fixes from 1.0 release into 1.1
- Added validation to 
- Made Paths null by default to fix error reporting
- Do not include default basePath in output. 
- Handle V2 import when produces comes after responses 
- Fix MakeServers for V2 
- Add settings parameter for BaseUrl
- Add support for null to GetJsonCompatibleString 
- Output multiple examples in V2 
- Exposed Settings in IOpenApiWriter interface to allow access to selected version when writing extensions. (Potentially a breaking change?)
=> A variety of bug fixes for 1.1 preview

src/Microsoft.OpenApi/Services/OpenApiVisitorBase.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, test/Microsoft.OpenApi.Tests/Walkers/WalkerLocationTests.cs
This allows visitors to process the OpenAPIDocument based on context of where an object exists within the document.
=> Added ContextKeys object to VisitorBase

src/Microsoft.OpenApi.Readers/OpenApiReaderSettings.cs, src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiV2Deserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3Deserializer.cs, test/Microsoft.OpenApi.Readers.Tests/TestCustomExtension.cs
When extensions use existing OpenAPI objects within there definition we need to know what version of the spec the document is.
=> Added spec version to signature of custom extension parsers

build.cmd, src/Directory.Build.props
Replaces #284 with a pull request for `vnext`. See the SourceLink section of:
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/
And the home page:
https://github.com/dotnet/sourcelink/
=> enable SourceLink

src/Microsoft.OpenApi/Expressions/CompositeExpression.cs, src/Microsoft.OpenApi/Expressions/RuntimeExpression.cs, test/Microsoft.OpenApi.Tests/Expressions/RuntimeExpressionTests.cs
=> Added support for runtime expressions embedded in string literals

src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiJsonWriterTests.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterAnyExtensionsTests.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiYamlWriterTests.cs
- Add WriteValue for DateTime type
- Fix WriteValue for DateTimeOffset type to convert to write as string with specific format. This will force it to be written just like string (ie. with double-quotes in JSON and single-quotes in YAML.)
- Add Tests
Fix #291
=> Fix WriteValue for DateTimeOffset to write as string (i.e. with quotes)

README.md
Adding a snippet about the shiny new OData processor. 🥇
=> Adding OData processor to readme.

src/Microsoft.OpenApi.Readers/V2/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiHeaderDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiParameterDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiAnyTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterAnyExtensionsTests.cs
Parse decimals and ints with InvariantCulture since JSON/YAML doesn't vary by culture.
For example, the parser should always treat 100.000 as one hundred, not one hundred thousand, even if the operating system on the machine is set to use French.
Fix #323
=> Parse decimals and ints with InvariantCulture since JSON/YAML doesn't vary by culture.

src/Microsoft.OpenApi/Services/OpenApiComparerBase.cs, src/Microsoft.OpenApi/Services/OpenApiComparerFactory.cs, src/Microsoft.OpenApi/Services/OpenApiComponentsComparer.cs, src/Microsoft.OpenApi/Services/OpenApiContactComparer.cs, src/Microsoft.OpenApi/Services/OpenApiDictionaryComparer.cs, src/Microsoft.OpenApi/Services/OpenApiDocumentComparer.cs, src/Microsoft.OpenApi/Services/OpenApiExternalDocsComparer.cs, src/Microsoft.OpenApi/Services/OpenApiInfoComparer.cs, src/Microsoft.OpenApi/Services/OpenApiLicenseComparer.cs, src/Microsoft.OpenApi/Services/OpenApiOAuthFlowComparer.cs, src/Microsoft.OpenApi/Services/OpenApiOAuthFlowsComparer.cs, src/Microsoft.OpenApi/Services/OpenApiOperationComparer.cs, src/Microsoft.OpenApi/Services/OpenApiOperationsComparer.cs, src/Microsoft.OpenApi/Services/OpenApiOrderedListComparer.cs, src/Microsoft.OpenApi/Services/OpenApiParameterComparer.cs, src/Microsoft.OpenApi/Services/OpenApiReferenceComparer.cs, src/Microsoft.OpenApi/Services/OpenApiRequestBodyComparer.cs, src/Microsoft.OpenApi/Services/OpenApiSchemaComparer.cs, src/Microsoft.OpenApi/Services/OpenApiSecurityRequirementComparer.cs, src/Microsoft.OpenApi/Services/OpenApiSecuritySchemeComparer.cs, src/Microsoft.OpenApi/Services/OpenApiTagComparer.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiComparerTestCases.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiComponentsTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiInfoComparerTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiParameterComparerTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiRequestBodyComparerTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiResponsesComparerTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiSecurityRequirementComparerTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiSecuritySchemeComparerTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiTagComparerTests.cs
Added comparison logic for
- OpenApiInfo
- OpenApiExternalDocs
- OpenApiSecurityRequirements
=> Added more comparers

src/Microsoft.OpenApi.Readers/V3/OpenApiHeaderDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiDocument/apiWithFullHeaderComponent.yaml
Specification says HeaderObject is a ParameterObject with some minor differences: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#headerObject
components/headers at the same time is defined as Map[string, Header Object \| Reference Object]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#componentsObject
which leads me to believe that components/headers should support full set of properties allowed for ParameterObject with exception of "name" and "in"
=> Supporting all header fields inside components/headers

src/Microsoft.OpenApi/Writers/SpecialCharacterStringExtensions.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterSpecialCharacterTests.cs
A trailing colon in a string causes the YAML parser to think the scaler is a map key.  This change ensures scalars with colons are quoted.  Arguably, we could allow colons in the middle of strings as long as they are not followed by a space but, this change should be sufficient.  Fixes #380
=> Cause scalar string with colon to be quoted #380

src/Microsoft.OpenApi.Readers/ParseNodes/OpenApiAnyConverter.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterAnyExtensions.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiExampleTests.cs
This PR trys to fix the issue at #386 .
Before this change, the library can't write the "byte[]" types.
=> write the binary to base64string and read it as byte[]

src/Microsoft.OpenApi.Readers/ParseNodes/OpenApiAnyConverter.cs, src/Microsoft.OpenApi/Any/OpenApiByte.cs, src/Microsoft.OpenApi/Any/OpenApiPrimitive.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterAnyExtensions.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiExampleTests.cs
1. Change OpenApiByte
2. Change OpenApiBinary
3. Chang the OpenApiByte & OpenApiBinary serialization/desalinization.
Below are the discussions:
@darrelmiller 
Admittedly, the schema is unnecessary, but there are examples in the spec that show this.  In this scenario the format: binary is used to indicate that there is no special serialization that is performed on the bytes.  They are raw.  If you try and present them as a string, they might not create printable text.
This is not a problem in 90% of cases because for the definition of an API you don’t need to include any data.  The spec says the parameter contains binary data and tooling knows not to do any processing on it.  That’s obviously potentially tricky if it is in a URL parameter! However, for us, the only place it causes a …
=> Change OpenApiByte & OpenApiBinary

src/Microsoft.OpenApi/Validations/Rules/RuleHelpers.cs
Fix #394 
Allow OpenApiNull as the data when schema specifies `nullable` as true
Note that this applies to all data types, even arrays, objects, and strings. Per JSON schema, objects, arrays, strings, etc. are separate from the null types. If the schema wants to allow the objects, arrays, etc. to be nullable, the nullable boolean must be specifically set to true. (In JSON schema, this is done by using type : ["array", "null"], which is not allowed in OpenAPI spec).
At its core, JSON Schema defines the following basic types:
string
Numeric types
object
array
boolean
null
Primitive data types in the OAS are based on the types supported by the JSON Schema Specification Wright Draft 00. Note that integer as a type is also supported and is defined as a JSON number without a fraction or …
=> Allow null as a valid data when schema.nullable is set to true

src/Microsoft.OpenApi/Models/OpenApiParameter.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs
When a parameter has the style set to "form" and explode set to false,
the v3 serializer will not write out the value for explode. Swagger UI
then defaults the explode value to true, since it is not specified and
that is the correct default value when the style is set to "form". The
OpenAPI spec for this is right around here:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-10
I'll be glad to make any changes required to get his accepted.
=> Serialize explode value properly on parameters with style "form"

README.md
I am proposing adding a nuget link to the Readers package to help developers understand that the OpenAPI.NET Reader classes require a separate nuget installation.
=> Updating README to include a link to Readers nuget

src/Microsoft.OpenApi.Readers/V2/OpenApiParameterDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/TempStorageKeys.cs
Change from a static variable to temp storage scoped to the parse
context to fix thread-safety issue in v2 parameter parsing.
Fixes #416
=> Use context specific storage for param parsing

src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, src/Microsoft.OpenApi.Readers/ParseNodes/ListNode.cs, src/Microsoft.OpenApi.Readers/ParseNodes/MapNode.cs, src/Microsoft.OpenApi.Readers/ParseNodes/ParseNode.cs, src/Microsoft.OpenApi.Readers/ParseNodes/PropertyNode.cs, src/Microsoft.OpenApi.Readers/ParseNodes/RootNode.cs, src/Microsoft.OpenApi.Readers/ParseNodes/ValueNode.cs, src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiSecurityRequirementDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiV2Deserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSecurityRequirementDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3Deserializer.cs, test/Microsoft.OpenApi.Readers.Tests/ParseNodes/OpenApiAnyConverterTests.cs, test/Microsoft.OpenApi.Readers.Tests/ParseNodes/OpenApiAnyTests.cs, test/Microsoft.OpenApi.Readers.Tests/TestHelper.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiSecuritySchemeTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiCallbackTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDiscriminatorTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiEncodingTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiExampleTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiInfoTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiSecuritySchemeTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiXmlTests.cs
Is there a reason to have Diagnostic on ParseNode rather than in context as in this PR? Judging from code they both go hand in hand always and I can't really see any valuable scenario when one would need to change diagnostic between nodes.
=> Diagnostic moved from MapNode to ParsingContext

src/Microsoft.OpenApi/Models/OpenApiResponse.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterExtensions.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiResponseTests.cs
Right now if empty response is provided it will be serialized as empty object thus producing invalid spec.
=> Always emitting description property for response object. It's required

src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, src/Microsoft.OpenApi.Readers/OpenApiStringReader.cs, src/Microsoft.OpenApi.Readers/OpenApiTextReaderReader.cs, src/Microsoft.OpenApi.Readers/OpenApiYamlDocumentReader.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiSecuritySchemeTests.cs
This is a small optimization to expose ability to read OpenAPI documents and fragments from TextReader. This allows one to parse string more efficiently without need to put it into memory stream first.
=> Small readers optimization

src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiResponseDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/TempStorageKeys.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/operationWithResponseExamples.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/twoResponses.json
Before the fix they were combined, but spec clearly says this should not be done: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-5
=> 'produces' at operation level must override one specified globally

src/Microsoft.OpenApi.Readers/ParseNodes/OpenApiAnyConverter.cs, src/Microsoft.OpenApi.Readers/ParseNodes/ValueNode.cs, src/Microsoft.OpenApi/Any/OpenApiString.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiExampleTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiInfoTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiExample/explicitString.yaml
If string value was specified in YAML explicitly via quotes, or one of the other string syntaxes it must not be converted into any other type.
=> Explicitly specified string must stay a string

src/Microsoft.OpenApi.Readers/ParseNodes/MapNode.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/ComponentRootReference.json
Attempt to fix #415 
This is only partial fix.  It does ensure that the object model is valid however, due to the way references are resolved we lose the fact that in the original document the reference was to AllPets as it gets collapsed down to Pets.  More investigation is required.
=> Collapsed components that are references

src/Microsoft.OpenApi/Models/OpenApiResponse.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiResponseTests.cs
Fixes issue #458. Augmented unit tests to assert the fix.
=> Fixes #458

Microsoft.OpenApi.sln, build.cmd, src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi.Tool/Microsoft.OpenApi.Tool.csproj, src/Microsoft.OpenApi.Tool/OpenApiService.cs, src/Microsoft.OpenApi.Tool/Program.cs, src/Microsoft.OpenApi/Any/OpenApiString.cs, src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs, src/Microsoft.OpenApi/Services/LoopDetector.cs, src/Microsoft.OpenApi/Services/OpenApiDifferenceOperation.cs, src/Microsoft.OpenApi/Writers/OpenApiJsonWriter.cs, test/Microsoft.OpenApi.SmokeTests/ApiGurus.cs
C:\ > openapi -h
Usage:
Microsoft.OpenApi.Tool [options]
Options:
--input <input>
--output <output>
--version <OpenApi2_0|OpenApi3_0>
--format <Json|Yaml>
--inline
=> Create dotnet commandline tool for performing conversions and inlining

src/Microsoft.OpenApi/Services/OpenApiWalker.cs
Proposes:
- Adding the missing `oneOf` child object in walker method for an `OpenApiSchema` to be able to extract out references within this object.
=> Adds missing oneOf child object in walker method for OpenApiSchema

src/Microsoft.OpenApi/Any/OpenApiString.cs
1.2.0 added an optional parameter on OpenApiString. This is a breaking change for indirect consumers resulting in a MissingMethodException.
=> Prevent breaking change on optional parameter #487

src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs, src/Microsoft.OpenApi/Writers/OpenApiJsonWriter.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, src/Microsoft.OpenApi/Writers/OpenApiYamlWriter.cs
This changes all overloads from https://github.com/microsoft/OpenAPI.NET/commit/f00c27cc0e104dd67ae26f85323950a7ae44e5d4 to be binary compatible for not having 1.2.0 break 1.1.4 upgrades
=> Make default parameter overloads binary compatible

src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, src/Microsoft.OpenApi/Writers/OpenApiYamlWriter.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterSpecialCharacterTests.cs
OpenAPI allows `description` to be written in Markdown. Markdown descriptions can be multiple lines.
Current `OpenApiYamlWriter` escapes all control characters and joins and serializes them in one line.
I read description from external `README.md` file, and put it to `document.Info.Description`, and publishes the generated OpenAPI document.
Users can `diff` with previous versions of documents to track any public changes.
However, it is quite daunting when you have to look these long concatenated Markdown description to find diffs.
With literal style block scalar, I can preserve my line breaks of `README.md` as is.
=> Add literal style support for OpenApiYamlWriter

test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/PublicApi/PublicApiTests.cs
This unit test will help protect against breaking changes in the public api.
How does it work? Using PublicApiGenerator it starts off from a well-known state of the API, generates the public contract for the current API and compares the two.
If the public API has been changed, the test will fail and a human is needed to evaluate if the change is breaking or not. This can then be used to determine if the new release number is a major or minor.
The new API surface needs to be updated to make the test succeed again and have a new well-known state.
=> Add public api surface test

src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, src/Microsoft.OpenApi/Extensions/OpenApiReferencableExtensions.cs, src/Microsoft.OpenApi/JsonPointer.cs, src/Microsoft.OpenApi/Services/OpenApiWorkspace.cs, test/Microsoft.OpenApi.Tests/Workspaces/OpenApiReferencableTests.cs, test/Microsoft.OpenApi.Tests/Workspaces/OpenApiWorkspaceTests.cs
- Add `IOpenApiReferenceable ResolveReference(JsonPointer pointer, JsonPointer pointerFromRoot = null);` method to `IOpenApiElement` interface.
- Add `OpenApiElementBase` class which containing an implementation of the `ResolveReference` method used by many of the classes which implement `IOpenApiElement`.
- Update implementation of `OpenApiWorkspace.ResolveReference` method to support referencing document fragments.
- UTs covering the above.
=> OpenAPI Workspace Document Fragments

src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs
I stumbled upon this issue while trying to parse OpenAPI docs from SAP. Within their docs they use scientific notation to describe percentages (ex. discounts). When trying to parse those docs a System.FormatException would be thrown due to the scientific notation. If I manually convert those values to their decimal equivalents (ex. 1.0e-3 == 0.003) everything works fine.
After researching this a bit I found that including the NumberStyles.Float flag in the call to Decimal.Parse() would address the issue without changing the handling of whole number input (ex. 1). This essentially tacks on the AllowExponent flag.
=> Support for scientific notation in parsing of "multipleOf" FixedFieldMap.

src/Microsoft.OpenApi/Any/OpenApiPrimitive.cs, src/Microsoft.OpenApi/Any/OpenApiString.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
#527 
Added parameter to OpenApiString that allows its value to be written raw without any encoding by the selected writer.
Modified the base OpenApiPrimitive string case to support the new OpenApiString.IsRawString() and select the correct writer.Write function.
=> Allow OpenApiString's raw value to be written by the OpenApiWriter

.github/dependabot.yml
- add `dependabot.yml` which automatically enables Dependabot's dependency versioning scanner and dependency update PRs bot by declaring dependency ecosystems and sources in the project. For dependency security vulnerabilities scanner and vulnerable dependency update PRs bot, [enable "Dependabot alerts" and "Dependabot security updates"](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates)
Resolves #564
=> Add security and versioning dependency alerts

src/Microsoft.OpenApi.Readers/V2/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs
I neglected to apply the NumberStyles.Float fix for supporting exponential notation to the V2 SchemaDeserializer. I also added it to the handling of Maximum and Minimum properties in both V2 and V3 SchemaDeserializer's as hey both leverage decimal.Parse().
=> Further exponential notation fix.

src/Microsoft.OpenApi.Readers/Exceptions/OpenApiReaderException.cs, src/Microsoft.OpenApi.Readers/ParseNodes/ListNode.cs, src/Microsoft.OpenApi.Readers/ParseNodes/MapNode.cs, src/Microsoft.OpenApi.Readers/ParseNodes/ParseNode.cs, src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi/Exceptions/OpenApiException.cs, test/Microsoft.OpenApi.Readers.Tests/ParseNodeTests.cs
Fixes #500
- Fixed issues with Pointer encoding and missing segments
```yaml
openapi: 3.0.0
info:
title: foo
version: bar
paths:
'/foo':
get:
responses:
200: 
description: ok
content:
application/json:  
schema: asdasd
```
Pointer needs to look like
```
#/paths/~1foo/get/responses/200/content/application~1json/schema
```
Previously slashes were not being escaped.  Also, map keys were not getting added to the path.  This affected `content`, `examples`, `headers`, `encoding`
- Added better documentation to the OpenApiException.Pointer property
- Converted OpenApiException to OpenApiReaderException in parsenodes so that line number is always included if JSON Pointer is not possible.
=> Fixes issues with the pointer in the OpenApiError object

src/Microsoft.OpenApi/Validations/Rules/OpenApiMediaTypeRules.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Validations/OpenApiMediaTypeValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/ValidationRuleSetTests.cs
Addresses #407 and #587  by disabling the validation rule by default
=> Removed DataTypeMismatch as default rule

src/Microsoft.OpenApi.Readers/OpenApiReaderSettings.cs, src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, test/Microsoft.OpenApi.Readers.Tests/OpenApiReaderTests/OpenApiStreamReaderTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET/issues/530
Closes https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/583
This PR:
- Adds a new `boolean` setting in `OpenApiReaderSettings.cs`: `LeaveStreamOpen` to flag whether or not to leave the stream object open after reading from an `OpenApiStreamReader` object.
Creating a `StreamReader` object within a `using` statement closes the `stream` when the `Dispose()` method of the `StreamReader` is called.
- Creates `OpenApiStreamReader` tests to validate setting the `LeaveStreamOpen` setting to either `true` or `false`.
=> Adds setting to configure leaving stream open

src/Microsoft.OpenApi.Tool/OpenApiService.cs, src/Microsoft.OpenApi.Tool/Program.cs, src/Microsoft.OpenApi/Services/OpenApiFilterService.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Services/OpenApiFilterServiceTests.cs
This PR proposes:
- Adding a `--filterByTag` command option to the `transform` command in the commandline tool
- Updates the `OpenApiFilterService`  with logic for slicing an OpenApiDocument based on the tags provided
- Adding tests to validate for filtering by `tags`
- Build the project and its dependencies by running the ` .\build.cmd` file
- Reinstall the `openapi-parser` tool locally by running the `.\install-tool.ps1` script
- Invoke the tool by running the .\artifacts\openapi-parser.exe file and call the transform command
- To use the new command option, append the `--filterByTags "tags"` parameter to the transform command
E.g: `.\artifacts\openapi-parser.exe transform --input Mail.yml --format yaml --output Mail2.yml --version OpenApi3_0 --filterByTags users.mailFolder`
Fixes #629
=> Adds --filterByTags Command option 

.azure-pipelines/ci-build.yml
This PR:
- Updates the current build.yml file with an additional build task for packaging the `OpenApi.Tool`, a commandline tool that enables processing of OpenAPI documents through validation, supports conversion for different file formats e.g from `json` to `yaml` and vice versa, and also supports filtering/slicing of OpenApi documents into smaller subset documents based on OperationIds and tags provided.
- This tool will then be published to Nuget as a package and leveraged across multiple projects such as DevX API, Kiota, Powershell, GE autocomplete etc
Fixes #630
=> Updates ci-build.yml to deploy Commandline tool to Nuget

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
This PR updates the `Microsoft.OpenApi` and `Microsoft.OpenApi.Readers` library versions from `1.3.0-preview` to `1.3.1-preview`
=> Bump up library versions

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
Issue: https://github.com/microsoft/OpenAPI.NET/issues/651
The  current `transform` command in Hidi defaults to `JSON` as the output format when no explicit format is specified. This is not the intended behaviour in most  cases.
This PR improves the `transform` command by using the default input file format and OpenApi version as the output format and version when no format or version is explicitly specified.
=> Use input file OpenApi format / version as the default output format / version in Hidi

src/Microsoft.OpenApi.Readers/V3/OpenApiEncodingDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiMediaTypeDeserializer.cs
Fixes for issue #683
1) Fix for parsing of encoding style.  
2) Add support for both null and empty media type objects:
```yaml
openapi: 3.0.1
info:
title: empty vs null media type objects
version: 1.0.0
paths:
"/":
get:
responses:
'200':
description: ok
content:
text/plain: {}
application/json: null
```
=> Fix round-tripping of empty media type objects and parsing of encoding style.

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs, src/Microsoft.OpenApi.Hidi/appsettings.json, test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj, test/Microsoft.OpenApi.Tests/Services/OpenApiFilterServiceTests.cs
As per [Kiota's documentation](https://microsoft.github.io/kiota/using.html), this PR seeks to align the common parameters between Hidi and Kiota in order to reduce any disparity in the tools.
As of now, these parameters are:
-  `--openapi` in Kiota  vs `--input` in Hidi representing the path to the OpenAPI description/CSDL file used to generate the code files
-  `--output` in Kiota vs `--output` in Hidi representing the output directory path for the generated code files
This PR also seeks to add aliases to our existing parameters for simplicity
Fixes #662
=> Align hidi params with kiota

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs
This PR upgrades Hidi to use the [System.Commandline 2.0 Beta 2](https://github.com/dotnet/command-line-api/issues/1537) package and resolves the breaking changes
Fixes #709
=> Upgrades to System.Commandline beta2

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
This update includes the alignment of parameters with kiota and some package updates.  The primary reason for the release is to test publishing because the previous previews of  hidi and openapi.readers did not actually get published.
=> Updated versions to preview3

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
=> Set Nuget properties in Hidi to align with compliance guidelines during publishing

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs, test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj, test/Microsoft.OpenApi.Tests/Services/OpenApiCSDLConversionTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiServiceTests.cs, test/Microsoft.OpenApi.Tests/UtilityFiles/Todo.xml
This feature enables consumption of CSDL files with the `.csdl` and `.xml` extensions as input in Hidi and therefore, slicing them based on the available parameters.
**Example**: `transform --input Files/Todo.xml --output Files/Todo-subset.yml --format yaml --version OpenApi3_0 --filterByOperationIds Todos.Todo.UpdateTodo`
Fixes #690
=> Convert csdl files to openapi

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs
Method returned void instead of Task and so would exit the app as soon as an async method was called.
Fixes #734
=> Fixed ValidateDocument method in hidi

.azure-pipelines/ci-build.yml
- Adds powershell script to fetch the version number from .csproj
- Adds a publish task for publishing hidi as a self-contained .exe application to the artifact staging directory
- Publish the generated artifact to the specified location
Fixes #731
=> Publish hidi as a self-contained application

src/Microsoft.OpenApi.Readers/ParsingContext.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiV2VersionService.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs, test/Microsoft.OpenApi.Readers.Tests/ReferenceService/ConvertToOpenApiReferenceV2Tests.cs, test/Microsoft.OpenApi.Readers.Tests/ReferenceService/ConvertToOpenApiReferenceV3Tests.cs
=> Catch any OpenApiExceptions thrown during parsing and continue processing Schema Components

.azure-pipelines/ci-build.yml
This PR pushes multiple improvements to the pipeline definition:
- Swaps ms build and vstest tasks by dotnet cli, to prepare an eventual transition to an ubuntu agent (performance) and for clarity
- Adds policheck, credscan, binskim, and antimalware scan tasks (compliance)
- Adds a deploy stage to avoid relying on the older release management, and use the same approbation rules defined in the environment across projects.
One thing I haven't included is the "has the version been bumped test" because I think further changes should be done to this pipeline:
- The deploy job should be splat into 3 jobs (deploy open API, deploy readers, deploy hidi) so each module can be deployed indenpendently from one another.
- Before each of those jobs, should be a reflective "check-openapi/reader/hidi …
=> updates pipeline definition to align with openapi.odata lib changes

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs
Fixes #784
- Passes the cancellation token from the system.command line host to async APIs to avoid getting task cancelled exceptions when users press ctrl + c
- Formats the logging to use templates instead of doing string interpolation so logging APIs can do sampling and metrics
=> Better error handling

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/OpenApiSpecVersionExtension.cs, src/Microsoft.OpenApi.Hidi/OpenApiSpecVersionHelper.cs, src/Microsoft.OpenApi.Hidi/Program.cs
=> Simplify openapi spec version for Hidi

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs
Fixes #783 
Currently, when a user provides a file path that already exists in their local file system as output in Hidi, it returns an error and tells them to provide a new path. This has been simplified by allowing one to use `--clean-ouput` parameter abbreviated as `-co` when running the transform command which overwrites the existing file by deleting its contents and replacing it with the new file.
=> Add --clean-output parameter to allow overwriting existing files

src/Microsoft.OpenApi.Hidi/CsdlFilter.xslt, src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs, test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj, test/Microsoft.OpenApi.Tests/Services/OpenApiServiceTests.cs
When working with large CSDL files, it can take a long time to generate the OpenAPI document.  For performance reasons this update adds a filter parameter so that a user can select a subset of the CSDL document.  This is done by providing a comma delimited list of EntitySet and Singleton names that appear in the EntityContainer.
```shell
hidi transform -cs dataverse.csdl --csdlFilter "appointments,opportunities" -o appointmentsAndOpportunities.yaml -ll trace
```
=> Added CSDL filter for entitysets and singletons

src/Microsoft.OpenApi/Models/OpenApiSchema.cs
=> Convert anyOf/oneOf to allOf with first schema when writing v2

src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs, test/Microsoft.OpenApi.Readers.Tests/ReferenceService/ConvertToOpenApiReferenceV3Tests.cs
Before the changes, if you pass `$ref: '../../smth'`, `ReferenceType` is found for the `OpenApiV3VersionService.ConvertToOpenApiReference()` call, and an error was thrown for every single openApiReference existing in the document (`The reference string '../schemas/api.json' has invalid format. [........]`)
=> [bugfix] Resolve local file reference with Schema type properly

src/Microsoft.OpenApi/Models/OpenApiDocument.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
This reverts a change that would have made this release a breaking change.
=> Made ResolveReference public again as it is used by Swashbuckle

src/Microsoft.OpenApi.Readers/OpenApiDiagnostic.cs, src/Microsoft.OpenApi.Readers/OpenApiYamlDocumentReader.cs, src/Microsoft.OpenApi/Extensions/OpenApiElementExtensions.cs, src/Microsoft.OpenApi/Validations/IValidationContext.cs, src/Microsoft.OpenApi/Validations/OpenApiValidatiorWarning.cs, src/Microsoft.OpenApi/Validations/OpenApiValidator.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiHeaderRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiMediaTypeRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiSchemaRules.cs, src/Microsoft.OpenApi/Validations/Rules/RuleHelpers.cs, src/Microsoft.OpenApi/Validations/ValidationExtensions.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Validations/OpenApiHeaderValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiMediaTypeValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiParameterValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/OpenApiSchemaValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/ValidationRuleSetTests.cs
Previously, OpenApiValidator only had the ability to report issues as Errors.  This PR adds a Warnings property and allows validation rules to create warnings instead of errors.  
All of the DataTypeMismatch rules have been updated to create Warnings instead of Errors.  
OpenApiDiagnostic that is returned when parsing an OpenAPI document now has a list of Errors and a list of Warnings.
=> Added support for Validation to produce warnings as well as errors

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs, src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs, src/Microsoft.OpenApi/Writers/OpenApiJsonWriter.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterSettings.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
Fixes #829 
Adds a --terse-ouput parameter, abbreviated as -to in Hidi to emit terse JSON output.
`transform -d C:\pestore.yaml -f json -o C:\pestore.json -co -to`
=> Add --terse-output Commandline parameter for producing JSON in terse format

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs
Fixes https://github.com/microsoft/OpenAPI.NET/issues/866
This PR:
- Adds a new OpenAPI convert setting `ExpandDerivedTypesNavigationProperties=false` to mitigate the generation of multiple navigation property paths for OData type cast paths which cause the StackOverflow exception reported in the aforementioned issue.
=> Adds OpenAPI convert setting `ExpandDerivedTypesNavigationProperties=false`

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Updates the `Microsoft.OpenApi.OData` lib version from `1.0.10` to `1.0.11-preview2`
Bumps up Hidi release version to `1.0.0-preview5`
=> Bumps conversion lib version and Hidi version

src/Microsoft.OpenApi/Writers/SpecialCharacterStringExtensions.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterSpecialCharacterTests.cs
* Added fn to check if a string is a c-style hex number
* Added logic for created fn to handling of special characters and wrap in quotes if true
* Added unit tests to check if writer prints the provided data.
=> Adding support to write c-style hex strings as strings

src/Microsoft.OpenApi.Readers/V2/OpenApiV2VersionService.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiContactTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiContactTests.cs
Currently, `OpenApiStringReader.ReadFragment<OpenApiContact>()` throws the following exception:
```
System.Collections.Generic.KeyNotFoundException : The given key 'Microsoft.OpenApi.Models.OpenApiContact'
was not present in the dictionary.
```
This is because `OpenApiV2/V3VersionService._loaders` does not have the entry of `[typeof(OpenApiContact)]`.
=> Add OpenApiContact for ReadFragment

.github/workflows/docker.yml, src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
=> - removes unecessary condition for get version step

src/Microsoft.OpenApi.Readers/V2/OpenApiPathItemDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiPathItemTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiPathItem/pathItemWithBodyPathParameter.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiPathItem/pathItemWithFormDataPathParameter.yaml
=> Add support for request body path parameters in v2

src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs
=> Treat an empty property name as valid

.azure-pipelines/ci-build.yml
This PR updates the Github release task by adding a condition `succeededOrFailed()` to ensure the task runs even if the preceding step fails.
Fixes #964
=> Fixes Missing Release Notes

src/Microsoft.OpenApi.Readers/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiV2VersionService.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs
Fixes #850 
When converting a schema to Open API v2, which contains either `oneOf` or `anyOf`, we add them as `allOf` if an `allOf` doesn't already exist, since both are not supported in v2.
The existing implementation failed to check if `anyOf` or `oneOf` existed before attempting to add `allOf`. This PR adds the check.
=> Fix anyOf and oneOf v2 serialization

src/Microsoft.OpenApi/Validations/Rules/OpenApiSchemaRules.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Validations/OpenApiSchemaValidationTests.cs
=> Fix parent schema discriminator validation

src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET/issues/992
This PR:
- Retrieves the `format` property value from the child schemas of `anyOf`, `oneOf` or `allOf` and appends this to the root schema when serializing as v2 (when writing items as properties). 
- Updates test to validate the above.
=> Appends `format` property value to root schema if contained in `anyOf`, `oneOf` or `allOf` when serializing as v2

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi.Readers/OpenApiYamlDocumentReader.cs
=> Separate warnings and errors in Open API YAML reader ReadAsync method

src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiExtensibleDictionary.cs, src/Microsoft.OpenApi/Models/OpenApiPaths.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
Fixes https://github.com/microsoft/OpenAPI.NET/issues/1007
This PR:
- Ensures `Paths` are copied in the copy constructor of `OpenApiDocument`.
- Adds test to validate the above.
=> Ensures `Paths` are copied in the copy constructor

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
bumps minor for hidi since the preview10 label is not considered a newer version than preview9 by nuget. https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=86423&view=logs&j=aa033440-3a4f-5530-5739-e7066bf05a26&t=384f8f03-5b5b-582f-91ea-efd11deadcd6
=> - bumps minor for hidi

src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Models/OpenApiResponses.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs
Fixes #995 
This PR:
- Ensures `Responses` are copied over in the `OpenApiOperation` copy constructor
- Adds a test case for validation 
- Bumps up lib version
=> Copy OpenApiResponses object from source OpenApiOperation

src/Microsoft.OpenApi/Services/OpenApiReferenceResolver.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Make OpenApiReferenceResolver public

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
Setting it to `1.4.4-preview1` so that it's consistent with the Object Model library and our current milestone
=> Bump up Readers version

src/Microsoft.OpenApi.Readers/V2/OpenApiV2Deserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiInfoDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiResponseDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3Deserializer.cs, src/Microsoft.OpenApi/Models/OpenApiInfo.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiInfoTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiInfo/advancedInfo.yaml, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiInfo/basicInfo.yaml, test/Microsoft.OpenApi.Tests/Models/OpenApiInfoTests.cs
This PR:
- Adds a Summary field to the OpenApiInfo object as per the [OpenAPI 3.1 spec](https://spec.openapis.org/oas/v3.1.0#info-object).
- Adds tests for validation
=> Adds a summary property in the info object

src/Microsoft.OpenApi.Readers/V3/OpenApiLicenseDeserializer.cs, src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiLicense.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiLicenseTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiLicense/licenseWithSpdxIdentifier.yaml, test/Microsoft.OpenApi.Tests/Models/OpenApiLicenseTests.cs
Adds a license identifier field in the license object for the [SPDX license expression](https://spec.openapis.org/oas/v3.1.0#license-object) for an API.
=> Add license SPDX identifier

src/Microsoft.OpenApi/Writers/SpecialCharacterStringExtensions.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterSpecialCharacterTests.cs
Writing version field depends on current system culture 
`version: '1.13.0'` for `en-US`
`version: 1.13.0` for `en-GB`
existing workaround:
set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` environment variable 
https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization#invariant-mode
=> fix: invariant culture for version field

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
This PR:
- Upgrades the conversion lib. version. This is to capture the fix https://github.com/microsoft/OpenAPI.NET.OData/pull/299
- Bumps up Hidi version
=> Upgrades conversion lib. version

src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs
Returning a null value once an exception is caught and added to the diagnostics object raises a `NullReferenceException` as the new `schema.Reference` object created during schema deserialization is assigned a null value when trying to convert the schema into an `OpenApiReference` object as shown [in this snippet](https://github.com/microsoft/OpenAPI.NET/blob/996dff454259178fb0d40e74a8c2741b3b7b9ab4/src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs#L279-L288).           
Meanwhile, there's an actual reference object considering a reference pointer is found in the schema. This means that the value of the '$ref' passed is either unsupported or incorrect.
Fixes #1045
=> Remove return statement to eliminate NullReference exception

.azure-pipelines/ci-build.yml, .github/workflows/ci-cd.yml, .github/workflows/codeql-analysis.yml, .vscode/launch.json, Dockerfile, src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj, test/Microsoft.OpenApi.Hidi.Tests/Microsoft.OpenApi.Hidi.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.SmokeTests/Microsoft.OpenApi.SmokeTests.csproj, test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> - upgrades to dotnet 7

src/Microsoft.OpenApi.Readers/Interface/IOpenApiVersionService.cs, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi.Readers/ParseNodes/MapNode.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiV2VersionService.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiExampleDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiHeaderDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiLinkDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiParameterDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiPathItemDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiRequestBodyDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiResponseDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSecurityRequirementDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiReference.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiDocument/documentWithSummaryAndDescriptionInReference.yaml, test/Microsoft.OpenApi.Tests/Models/OpenApiInfoTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
- Adds `summary` and `description` fields to the Reference object whose values by default SHOULD override those of the referenced component.
- Adds test to validate this.
=> Add summary and description to OpenApiReference object

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Validations/OpenApiValidator.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> - adds missing validation methods

src/Microsoft.OpenApi/Extensions/OpenApiTypeMapper.cs, test/Microsoft.OpenApi.Tests/Extensions/OpenApiTypeMapperTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Add support for OpenAPI schema generation for POCOs

src/Microsoft.OpenApi.Hidi/Handlers/TransformCommandHandler.cs, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiServiceTests.cs
Adds logic to enable process termination by getting an `IConsole` instance which enables us to listen for the breaking combination `CTRL+C` and using a `CancellationToken` to register cancellation and abort the process.
Fixes #884 
Reference: https://github.com/dotnet/command-line-api/issues/1750#issuecomment-1146502468
=> Enable termination of Hidi processes through pressing the breaking key combinations

test/Microsoft.OpenApi.Tests/Models/OpenApiCallbackTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiExampleTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiHeaderTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiLinkTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiRequestBodyTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiResponseTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSecuritySchemeTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiTagTests.cs
Verify supports StringWriter. no need to convert it to a string
=> verify string writer

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiServiceTests.cs
Uses `Path.DirectorySeparatorChar`, a platform-specific directory separator character to construct the absolute uri path to an Open API document for parsing during validation and transformation.
Should fix #1142 
Reference: https://learn.microsoft.com/en-us/dotnet/api/system.io.path.directoryseparatorchar?view=net-7.0
=> Fix hidi validator error when loading unix paths

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Models/OpenApiContact.cs, src/Microsoft.OpenApi/Models/OpenApiExternalDocs.cs, src/Microsoft.OpenApi/Models/OpenApiLicense.cs, src/Microsoft.OpenApi/Models/OpenApiOAuthFlow.cs, src/Microsoft.OpenApi/Models/OpenApiSecurityScheme.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiYamlWriterTests.cs
the constructor that was used [assumes absolute URLs](https://learn.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=net-7.0#system-uri-ctor(system-string)) (see the remarks section) which make validation fail
=> - fixes a bug where copy constructors would fail on relative urls

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Bumps up the `Microsoft.OpenApi.OData` lib. `v1.2.0` to `v1.3.0-preview2`
=> [Upgrade] Bumps up conversion lib version

src/Microsoft.OpenApi.Hidi/OpenApiService.cs
Fixes #1177 
Supported apps are passing in their settings to get more specialised details.
If no settings are passed, the default open api conversion settings in the conversion lib are used.
This makes it possible for other apps to only care about what they want instead of checking whether their preferences match the default kiota settings that were baked in
=> Feature: removes default conversion settings

src/Microsoft.OpenApi.Readers/OpenApiYamlDocumentReader.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSecuritySchemeDeserializer.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiDocument/docWithSecuritySchemeReference.yaml
This PR adds logic for resolving a security scheme reference object in the `components` section which previously was generating an error.
Fixes #1166
=> Fix: Error generated when security scheme in Components is a reference

test/Microsoft.OpenApi.Tests/PublicApi/PublicApiTests.cs
Replaces the obsolete ApiGeneratorOption `WhitelistedNamespacePrefixes` with `AllowNamespacePrefixes` for assembly generation
=> Replaces obsolete ApiGenerator option

src/Microsoft.OpenApi.Hidi/Handlers/TransformCommandHandler.cs, src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Program.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiServiceTests.cs
Adds the commandline option `--metadata-version` which takes in a metadata version parameter to be passed as a convert setting during CSDL to OpenApi conversion
Fixes #1196
=> Add a commandline option that takes in a metadata version for OpenAPI conversion

src/Microsoft.OpenApi.Readers/V2/OpenApiDocumentDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiServerTests.cs
according to [the spec](https://swagger.io/specification/v2/) the base path should be defaulted to the description path value ONLY when the host is NOT provided
=> - fixes a bug where the base path would be forcibly set to the description

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Helpers/DictionaryCloneHelper.cs, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
Modifies the `DictionaryCloneHelper's` `Clone()` method to keep track of cloned objects in order to avoid recursively cloning an object afresh that's already been cloned using reflection. This reduces circular dependencies caused by recursion that lead to StackOverflowExceptions.
=> Track cloned objects to avoid StackOverflowExceptions during cloning

src/Microsoft.OpenApi.Readers/V3/OpenApiPathItemDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/ReferenceType.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, test/Microsoft.OpenApi.Readers.Tests/ReferenceService/ConvertToOpenApiReferenceV3Tests.cs
Took a stab at implementing the case where tha path is an external reference, see issue #1228.
=> Issue #1228 path as reference to external

src/Microsoft.OpenApi/Models/OpenApiSchema.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Clone extensions in the OpenApiSchema copy constructor

src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiFilterServiceTests.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiServiceTests.cs
This PR fixes a bunch of hard-coded "\" separators in the tests that caused many failures when running on MacOS (maybe also on Linux?).
There is still one test failing on my MacOS system, OpenApiWorkspacesShouldNormalizeDocumentLocations. It looks like the value of `Environment.CurrentDirectory` is returning a different value on my system -- it adds "/net7.0" where the test appears not to expect this.
=> Fix hardcoded non-portable path separators

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi.Readers/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiResponseDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiV2Deserializer.cs, src/Microsoft.OpenApi/Services/OpenApiReferenceResolver.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/operationWithBodyAndEmptyConsumes.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/operationWithEmptyProducesArrayInResponse.json
=> Fix missing response schema bug

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi.Readers/OpenApiReaderSettings.cs, src/Microsoft.OpenApi/Extensions/StringExtensions.cs, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiDeprecationExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiEnumFlagsExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiEnumValuesDescriptionExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiPagingExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiPrimaryErrorMessageExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiReservedParameterExtension.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiDeprecationExtensionTests.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiEnumFlagsExtensionTests.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiEnumValuesDescriptionExtensionTests.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiPagingExtensionsTests.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiPrimaryErrorMessageExtensionTests.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiReservedParameterExtensionTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
related https://github.com/microsoft/kiota/issues/3066
=> moves all microsoft extensions to a single place

.azure-pipelines/ci-build.yml, .vscode/settings.json, src/Microsoft.OpenApi.Hidi/Extensions/OpenApiExtensibleExtensions.cs, src/Microsoft.OpenApi.Hidi/Extensions/StringExtensions.cs, src/Microsoft.OpenApi.Hidi/Formatters/PowerShellFormatter.cs, src/Microsoft.OpenApi.Hidi/Handlers/PluginCommandHandler.cs, src/Microsoft.OpenApi.Hidi/Handlers/ShowCommandHandler.cs, src/Microsoft.OpenApi.Hidi/Handlers/TransformCommandHandler.cs, src/Microsoft.OpenApi.Hidi/Handlers/ValidateCommandHandler.cs, src/Microsoft.OpenApi.Hidi/Logger.cs, src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/Options/FilterOptions.cs, src/Microsoft.OpenApi.Hidi/Options/HidiOptions.cs, src/Microsoft.OpenApi.Hidi/Program.cs, src/Microsoft.OpenApi.Hidi/StatsVisitor.cs, src/Microsoft.OpenApi.Hidi/Utilities/SettingsUtilities.cs, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Extensions/OpenApiExtensibleExtensions.cs, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Models/OpenApiParameter.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterSettings.cs, test/Microsoft.OpenApi.Hidi.Tests/Microsoft.OpenApi.Hidi.Tests.csproj, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiFilterServiceTests.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiServiceTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiServerTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiUrlTreeNodeTests.cs
- - enables NRT for main hidi project
- - enables all mode analysis
=> enables NRT, analysis all and treat warning as errors on hidi

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Bumps hidi version to release changes made in https://github.com/microsoft/OpenAPI.NET.OData/pull/430
=> Bump hidi version

test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiPrimaryErrorMessageExtensionTests.cs
Unblocks release build at https://github.com/microsoft/OpenAPI.NET/pull/1393 due to obsolete warnings
Refactors tests to fix obsolete warnings
=> Fix warnings blocking release

.github/workflows/ci-cd.yml, src/Microsoft.OpenApi/Services/OpenApiWorkspace.cs, test/Microsoft.OpenApi.Tests/StringExtensions.cs
Current CI does not fail on test failures but returns a false positive. See example at https://github.com/microsoft/OpenAPI.NET/actions/runs/6405608929/job/17388529486?pr=1393
This PR cleans up the workflow to 
- remove deployment stage(this is handled by separate ADO pipeline)
- Fix CI validation to build and test the project 
Failing test on dev branch have been fixed as well to unblock Hidi release via https://github.com/microsoft/OpenAPI.NET/pull/1393
=> Fixes PR validation

src/Microsoft.OpenApi/Writers/SpecialCharacterStringExtensions.cs
Changed collection types to either Dictionary or HashSet from arrays where lookups are used.
Keeping single collection definition over yaml control characters.
=> Use lookup collections

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Bumps up the conversion lib version to: `1.5.0-preview8`
https://www.nuget.org/packages/Microsoft.OpenApi.OData/1.5.0-preview8
=> Bump up conversion lib version

src/Microsoft.OpenApi.Readers/ParseNodes/ParserHelper.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiHeaderDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiParameterDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/ParseNodes/ParserHelperTests.cs
Sometimes developers put Double.MaxValue or Long.MaxValue asmax values for numbers in json schema, even if their numbers are not expected to be that big/small.  As we have already released the library with Decimal type for Max/Min, let's not introduce the breaking change and just fallback to Decimal.Max / Min in case of overflow. This should satisfy almost every scenario. We can revisit this if somebody really needs to have double or long here.
Fixing this exception stacktrace
ExceptionType: System.OverflowException
ExceptionMessage:      Value was either too large or too small for a Decimal.
InnerExceptionType:    
InnerExceptionMessage: 
StackTrace: 
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
at System.Decimal.Parse(String s, NumberStyles style, …
=> Handle number overflow during parsing of min/max values

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi.Hidi/Utilities/SettingsUtilities.cs, src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
=> Configure Hidi --settings-file path to be relative to the current working directory

test/Microsoft.OpenApi.Readers.Tests/ParseNodes/ParserHelperTests.cs
Fixes a problem when the tests are failing because the test input is generated with a culture dependend input. 
This happens on for example german systems because the dot is replaced with a comma and therefore a FormatException is throw.
=> Fix culture dependency in ParseDecimalWithFallbackOnOverflow_Overflows_ReturnsFallback test

src/Microsoft.OpenApi/Any/OpenApiPrimitive.cs, test/Microsoft.OpenApi.Tests/Writers/OpenApiJsonWriterTests.cs
=> Fix: OpenApiJsonWriter produces non-standard JSON values when a schema has 'NaN' or 'Infinity' values

src/Microsoft.OpenApi.Readers/ParseNodes/OpenApiAnyConverter.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiDocument/documentWithDateExampleInSchema.yaml
- Inspects the `TimeOfDay` property of a `DateTimeOffSet` value in an example object during parsing to determine whether it's a `date-only` or `date-time` type. 
-  If the time component is exactly midnight(00:00:00) meaning no time has elapsed, we conclude that it is a date-only value hence cast it to an `OpenApiDate` type, otherwise its converted to an `OpenApiDateTime` object.
- Fixes #1526
=> Fix data and type mismatch warning for an example object with a date value

src/Microsoft.OpenApi/Validations/Rules/OpenApiPathsRules.cs
6bda890fc7f19db283123a7aa4327b2cc39bc99e introduced a Timeout on RegEx compilation. We hit this timeout a few times since this change.
Removed the timeout so it uses the default like before.
Stacktrace:
```
System.Text.RegularExpressions.RegexMatchTimeoutException: The Regex engine has timed out while trying to match a pattern to an input string. This can occur for many reasons, including very large inputs or excessive backtracking caused by nested quantifiers, back-references and other factors.
at System.Text.RegularExpressions.RegexRunner.<CheckTimeout>g__ThrowRegexTimeout|25_0()
at Regex5_TryMatchAtCurrentPosition(RegexRunner, ReadOnlySpan`1)
at Regex5_Scan(RegexRunner, ReadOnlySpan`1)
at System.Text.RegularExpressions.Regex.RunAllMatchesWithCallback[TState](String inputString, …
```
=> fix possible RegexMatchTimeoutException

src/Microsoft.OpenApi.Readers/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiParameterDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/OpenApiResponseDeserializer.cs, src/Microsoft.OpenApi.Readers/V2/TempStorageKeys.cs, src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiExample.cs, src/Microsoft.OpenApi/Models/OpenApiParameter.cs, src/Microsoft.OpenApi/Models/OpenApiRequestBody.cs, src/Microsoft.OpenApi/Models/OpenApiResponse.cs, src/Microsoft.OpenApi/Writers/IOpenApiWriter.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/opWithBodyParameterExamples.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/opWithResponseExamplesExtension.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/v3OperationWithBodyParameterExamples.yaml, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiOperation/v3OperationWithResponseExamples.yaml, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.SerializeParameterWithSchemaReferenceAsV2JsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.SerializeParameterWithSchemaReferenceAsV2JsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.SerializeParameterWithSchemaTypeObjectAsV2JsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.SerializeParameterWithSchemaTypeObjectAsV2JsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
This is a rebase of #1524 on our `vnext` branch since its not a breaking change
=> Fix: Examples serialization in a response object during v2->v3 upcasting or vice versa

src/Microsoft.OpenApi.Readers/OpenApiStreamReader.cs, test/Microsoft.OpenApi.Readers.Tests/OpenApiReaderTests/OpenApiStreamReaderTests.cs
=> Fix OpenApiStreamReader.ReadAsync doesn't respect "leave open" setting

src/Microsoft.OpenApi/Helpers/JsonNodeCloneHelper.cs, src/Microsoft.OpenApi/Models/OpenApiExample.cs, src/Microsoft.OpenApi/Models/OpenApiHeader.cs, src/Microsoft.OpenApi/Models/OpenApiMediaType.cs, src/Microsoft.OpenApi/Models/OpenApiParameter.cs, src/Microsoft.OpenApi/Models/References/OpenApiExampleReference.cs, src/Microsoft.OpenApi/Reader/Services/OpenApiRemoteReferenceCollector.cs, test/Microsoft.OpenApi.Tests/Models/References/OpenApiExampleReferenceTests.cs
=> Fixes cloning of `JsonNode` objects

src/Microsoft.OpenApi/Extensions/OpenApiTypeMapper.cs
Fixes the default schema mappings used to generate schemas for nullable types by removing the `anyOf` keyword and using a types array that defines multiple schema value types in line with JSON schema.
=> Fix default mappings for nullable types

.github/CODEOWNERS
- replaces baywet by coseguera since he is now the crew leader
=> - removes peter from code owners

src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Reader/OpenApiJsonReader.cs, src/Microsoft.OpenApi/Services/HostDocumentResolver.cs, src/Microsoft.OpenApi/Services/JsonSchemaReferenceResolver.cs, src/Microsoft.OpenApi/Services/ReferenceHostDocumentSetter.cs, test/Microsoft.OpenApi.Readers.Tests/OpenApiReaderTests/OpenApiDiagnosticTests.cs, test/Microsoft.OpenApi.Readers.Tests/OpenApiWorkspaceTests/OpenApiWorkspaceStreamTests.cs, test/Microsoft.OpenApi.Readers.Tests/ReferenceService/TryLoadReferenceV2Tests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/JsonSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Workspaces/OpenApiWorkspaceTests.cs
This PR:
- Partially closes https://github.com/microsoft/OpenAPI.NET/issues/1613
- Removes `JsonSchema` reference resolution step when parsing a doc.
- Splits `JsonSchema` reference resolution from the reference host document setting into separate classes.
- Updates some tests in line with the above changes.
- Deletes some tests that were not relevant in light of the above changes.
**NB:** By removing `JsonSchema` reference resolution, we now don't validate whether the `JsonSchema` references concrete instances are defined in the `components/schemas` section of a document (locally or externally).
=> Removes `JsonSchema` reference resolution when parsing a doc.

src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Reader/Services/OpenApiWorkspaceLoader.cs, src/Microsoft.OpenApi/Reader/V2/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi/Reader/V3/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi/Services/OpenApiComponentsRegistryExtensions.cs, test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj, test/Microsoft.OpenApi.Tests/Models/References/OpenApiPathItemReferenceTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
Fixes https://github.com/microsoft/OpenAPI.NET/issues/1632
=> Register and retrieve `JsonSchema` references with `$id` value pointers 

.azure-pipelines/ci-build.yml, src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Fixes failing Nuget deploy step by adding a package parent path argument
=> Add a package parent path argument

.vscode/launch.json
Fixes launch `args` so it does not contain an absolute windows path, but relative path from the workspace folder
=> Change to relative path in `Launch Hidi` task

src/Microsoft.OpenApi.Hidi/Handlers/ValidateCommandHandler.cs, src/Microsoft.OpenApi.Hidi/OpenApiService.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiServiceTests.cs, test/Microsoft.OpenApi.Hidi.Tests/UtilityFiles/InvalidSampleOpenApi.yml
The previous related PR #1145 did return an exit code, but it did not use the result of the validation. This PR fixes this behavior.
This properly fixes #900 and #1141.
=> Return -1 exit code when the document is not valid

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
=> Updates conversion lib. version

src/Microsoft.OpenApi/Properties/SRResource.Designer.cs, src/Microsoft.OpenApi/Properties/SRResource.resx, src/Microsoft.OpenApi/Services/OpenApiReferenceResolver.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiDocument/docWithWrongRef.json
=> Fix invalid reference bug

src/Microsoft.OpenApi.Readers/V2/OpenApiV2Deserializer.cs, src/Microsoft.OpenApi.Readers/V3/OpenApiV3Deserializer.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiDeprecationExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiEnumFlagsExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiEnumValuesDescriptionExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiPagingExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiPrimaryErrorMessageExtension.cs, src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiReservedParameterExtension.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiReservedParameterExtensionTests.cs
=> Fixes null extension bug

src/Microsoft.OpenApi/Services/OpenApiFilterService.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiServiceTests.cs
Closes #1732.
Before this, callingOpenApiFilterService.CreateFilteredDocument on a document that does not contain the optional field OpenApiDocument.Components produces a NullReferenceException.
=> Fix OpenApiFilterService.CreateFilteredDocument failing when the Components field is missing.

README.md
Remove link to obsolete AppVeyor build (last build was 6 years ago!).
=> Remove redundant section from README

src/Microsoft.OpenApi/Any/OpenApiAnyCloneHelper.cs, src/Microsoft.OpenApi/Any/OpenApiArray.cs, src/Microsoft.OpenApi/Any/OpenApiObject.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs
- Fix `OpenApiArray` and `OpenApiObject` not copying their items when they are copied to a new instance.
- Add tests for all built-in `IOpenApiAny` types with schema examples.
Found as part of https://github.com/dotnet/aspnetcore/issues/56318#issuecomment-2238704199.
=> Fix copy constructor for arrays and objects

src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj, test/Microsoft.OpenApi.SmokeTests/Microsoft.OpenApi.SmokeTests.csproj
Aims to fix the error in the build task in the AzDo pipeline:
```
Error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.ApiAlertAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.'.
```
```
CSC : error AD0001: Analyzer 'Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers.ApiAlertAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.CodeAnalysis.VisualBasic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file …
```
=> Add missing nuget lib refs

src/Microsoft.OpenApi/Models/OpenApiReference.cs, src/Microsoft.OpenApi/Models/OpenApiSecurityRequirement.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSecurityRequirementTests.SerializeSecurityRequirementAsV3JsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSecurityRequirementTests.SerializeSecurityRequirementAsV3JsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSecurityRequirementTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSecuritySchemeTests.SerializeReferencedSecuritySchemeAsV3JsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSecuritySchemeTests.SerializeReferencedSecuritySchemeAsV3JsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSecuritySchemeTests.cs
Fixes the invalid serialization of the securityScheme reference from issue #1506 
The security requirement should not use the full serialization of a securityScheme as those are not the same. The securityRequirement only needs the reference to the securityScheme, not the complete object.
=> Fix securityScheme/securityRequirement serialization

src/Microsoft.OpenApi/Models/OpenApiMediaType.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiMediaTypeTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiMediaType/examplesWithEmptyArray.json
=> Fix example value of an empty array disappears after serialization

src/Microsoft.OpenApi/Interfaces/IOpenApiAnnotatable.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
Addresses https://github.com/microsoft/OpenAPI.NET/issues/1719.
This PR adds support for unserizable property bags to the `OpenApiDocument,`OpenApiOperation`, and `OpenApiSchema` to support managing in-memory metadata about a given OpenAPI instance without having these properties embedded into the serialized document.
- I landed on `Annotations` and `IOpenApiAnnotatable` as the names used in this API to align with the "ble" naming style used elsehwere. Open to other name ideas.
- `Annotations` are not eagerly initialized by the API to avoid allocating them when not necessary. It's up to the end-user to initialize the dictionary before appending elements to it.
- The interface is applied only to the `OpenApiDocument`, `OpenApiOperation`, and `OpenApiSchema` types at the moment to support …
=> Add support for unserializable annotations on OpenAPI document

src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Reader/ParseNodes/ParserHelper.cs, src/Microsoft.OpenApi/Reader/V2/OpenApiParameterDeserializer.cs, src/Microsoft.OpenApi/Reader/V2/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Reader/V3/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiV31VersionService.cs, test/Microsoft.OpenApi.Readers.Tests/ParseNodes/ParserHelperTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/jsonSchema.json, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
This PR:
- Adds a JSON schema model class with all known keywords
- Implements deserialization of V2, V3 and V31 OpenApi files into the in-memory Object model
- Implements serialization for V2, V3 and V31 keywords
- Adds tests
Fixes #1733, #1763, #1764, #1765
=> Add JSON schema support

.azure-pipelines/ci-build.yml
=> Fix: Remove minimatch pattern to sign all assemblies

src/Microsoft.OpenApi/Services/CopyReferences.cs, src/Microsoft.OpenApi/Services/OpenApiFilterService.cs, test/Microsoft.OpenApi.Hidi.Tests/Microsoft.OpenApi.Hidi.Tests.csproj, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiFilterServiceTests.cs, test/Microsoft.OpenApi.Hidi.Tests/UtilityFiles/docWithReusableHeadersAndExamples.yaml
=> Copy over references for all IOpenApiReferenceable objects

src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs
=> Fix: Do not default to an empty list if Security scheme is missing

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
=> Disable VisualStudio.Threading analyzers to eliminate build failures downstream

src/Microsoft.OpenApi/Services/OpenApiUrlTreeNode.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiUrlTreeNodeTests.cs
fixes #1580
This is a very naïve attempt at supporting trailing slashes in paths.
Please let me know if there are other cases that would need to be covered by the tests, or if this implementation would break in specific scenarios.
=> Support trailing slashes in paths

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Services/OpenApiFilterService.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiFilterServiceTests.cs
Fixes https://github.com/microsoft/OpenAPI.NET/issues/1840
=> Fixes duplication of path parameters during filtering subset doc.

src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiSchemaDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/schemaWithNullable.yaml, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/schemaWithNullableExtension.yaml, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/schemaWithTypeArray.yaml, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Handle upcasting and downcasting of JSON schemas with type arrays

src/Microsoft.OpenApi/Reader/OpenApiJsonReader.cs, src/Microsoft.OpenApi/Reader/Services/DefaultStreamLoader.cs
- Sets the workspace baseUrl when creating a workspace using the BaseUrl passed in settings. If not default to `OpenApiConstants.BaseRegistryUrl`
- Use current working directory to resolve file paths if baseUrl matches the default BaseRegistryUrl
Fixes:
- #1838
- #1839
=> Set workspace baseUrl when creating a workspace 

src/Microsoft.OpenApi/Models/OpenApiReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiV31Deserializer.cs, test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/Samples/docWithDollarId.yaml
=> Fix $ref with $id serialization

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi.Hidi/OpenApiSpecVersionHelper.cs
=> Allow hidi to transform an OpenAPI 3.1 document

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Bumps up Hidi to make use of the new `Microsoft.OpenAPI.OData` lib. version `2.0.0-preview3`
=> Bumps up Hidi version

src/Microsoft.OpenApi/Reader/ParsingContext.cs
=> Remove validation rule to make paths and webhooks optional

src/Microsoft.OpenApi/Reader/OpenApiModelFactory.cs
JSON data can be read asynchronously, which means that when you receive a stream of JSON data (e.g., from a file, network, or database), you can process the data directly without needing to load it all into memory first.
This increases efficiency by reducing memory usage and allowing the program to respond faster, especially in cases with large or streaming data.
In contrast, YAML does not support asynchronous reading in most libraries, requiring the data to be fully buffered before processing it synchronously.
Fixes #1853
=> Avoid buffering JSON data into a new MemoryStream during parsing

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Bumps and releases Hidi to make use of the conversion lib. 2.0.0-preview.6
=> Bump, Release Hidi

src/Microsoft.OpenApi/Utils.cs
use `nameof` for `CallerArgumentExpression`
=> use nameof for CallerArgumentExpression

src/Microsoft.OpenApi.Workbench/MainModel.cs, src/Microsoft.OpenApi.Workbench/MainWindow.xaml
=> Update workbench tool to parse 3.1 and YAML docs

src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiV31Deserializer.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterExtensions.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/schemaWithJsonSchemaKeywords.yaml, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
This PR:
- Removes the `recursiveRef` and `recursiveAnchor` keywords from our `OpenApiSchema` model as they're not supported in the latest JSON schema 2020-12 draft
- Updates the `Vocabulary` property type in our model to represent a dictionary; cleans up the serialization and deserialization of said property
- Cleans up our V3.1 serialization logic to ensure all supported JSON schema keywords are correctly written out
- Adds a test to validate the above
=> OpenApiSchema refactor to remove recursive keywords

src/Microsoft.OpenApi/Models/OpenApiDocument.cs
This PR fixes the link to the OpenAPI specification to use the official OAI version.
=> Fix link to OpenAPI specification

src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiSchemaDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/schemaWithConst.json, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Add support for JSON schema `const` keyword in OpenApiSchema

.azure-pipelines/ci-build.yml
=> Fix: Adds missing security metadata to the pipeline

src/Microsoft.OpenApi.Readers/OpenApiYamlReader.cs, src/Microsoft.OpenApi/Models/OpenApiTag.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiTagTests.SerializeAdvancedTagAsV2JsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiTagTests.SerializeAdvancedTagAsV2JsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiTagTests.SerializeAdvancedTagAsV3JsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiTagTests.SerializeAdvancedTagAsV3JsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiTagTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Fix tags serialization bug

src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterExtensions.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/schemaWithJsonSchemaKeywords.yaml, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Add support for handling unrecognized keywords

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
context hidi version 1.4.16 and 1.14.15 are actually based off v2 and anything odata related to odata won't work anymore until we have a preview of yoko, this aligns with the preview version to avoid confusion
=> fix: sets hidi version to a preview

src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiEnumValuesDescriptionExtension.cs, test/Microsoft.OpenApi.Tests/MicrosoftExtensions/OpenApiEnumValuesDescriptionExtensionTests.cs
=> fix: enum description number values

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi.Readers/OpenApiYamlReader.cs
reflection of https://github.com/microsoft/OpenAPI.NET/pull/1744, on a side note, we should probably multi-target our unit tests to include netfx before GA
=> fix: specifies encoding for net fx

src/Microsoft.OpenApi/Reader/OpenApiDiagnostic.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
I assume this was neither meant to be public nor meant to be in the global namespace. I noticed this when trying the latest preview because it conflicted with our own AddRange extension method.
This was introduced in #1245 and made public in https://github.com/microsoft/OpenAPI.NET/commit/90dc7fc5587cee40f5964919387baa3bafd8b9d8#diff-65294c3e990da88445c0036dfe9f8e7bcfb00675881d47c22fb3c6000c3b9d76R56 .
=> make IDiagnosticExtensions internal and fix namespace

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
Releases Hidi with respect to 1.X.  See related PR https://github.com/microsoft/OpenAPI.NET.OData/pull/642
=> Chore: Releases Hidi with respect to 1.X

src/Microsoft.OpenApi/Models/OpenApiSchema.cs
=> fix: a flaky behaviour for format property serialization

src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, src/Microsoft.OpenApi/Models/OpenApiRequestBody.cs, src/Microsoft.OpenApi/Models/References/OpenApiRequestBodyReference.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiOperationTests.cs
fixes a bug where OpenAPI v2 body parameter references would not serialize properly and always inline the definition
=> fixes OpenAPI v2 request body parameter references serialization

src/Microsoft.OpenApi/Models/References/OpenApiResponseReference.cs
partial #1998
@MaggieKimani1 could you stand additional PRs for the missing reference types here please? (search for the symbols on the Target property in the interface, then look at the body of the Target getter implementation
=> fixes OpenAPI response reference duplicating objects

src/Microsoft.OpenApi.Hidi/StatsVisitor.cs, src/Microsoft.OpenApi.Workbench/StatsVisitor.cs, src/Microsoft.OpenApi/Interfaces/IOpenApiReferenceHolder.cs, src/Microsoft.OpenApi/Models/Interfaces/IOpenApiCallback.cs, src/Microsoft.OpenApi/Models/OpenApiCallback.cs, src/Microsoft.OpenApi/Models/OpenApiComponents.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, src/Microsoft.OpenApi/Models/References/OpenApiCallbackReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiExampleReference.cs, src/Microsoft.OpenApi/Reader/V3/OpenApiCallbackDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiCallbackDeserializer.cs, src/Microsoft.OpenApi/Services/CopyReferences.cs, src/Microsoft.OpenApi/Services/OpenApiVisitorBase.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, src/Microsoft.OpenApi/Validations/OpenApiValidator.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiCallbackTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Visitors/InheritanceTests.cs
partial #1998, review #2089 first
=> fix: callback reference proxy implementation

src/Microsoft.OpenApi.Hidi/StatsVisitor.cs, src/Microsoft.OpenApi.Workbench/StatsVisitor.cs, src/Microsoft.OpenApi/Models/Interfaces/IOpenApiLink.cs, src/Microsoft.OpenApi/Models/OpenApiComponents.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiLink.cs, src/Microsoft.OpenApi/Models/OpenApiResponse.cs, src/Microsoft.OpenApi/Models/References/OpenApiCallbackReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiExampleReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiLinkReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiResponseReference.cs, src/Microsoft.OpenApi/Reader/V3/OpenApiLinkDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiLinkDeserializer.cs, src/Microsoft.OpenApi/Services/CopyReferences.cs, src/Microsoft.OpenApi/Services/OpenApiVisitorBase.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, src/Microsoft.OpenApi/Validations/OpenApiValidator.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiLinkTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Visitors/InheritanceTests.cs
partial #1998, review #2091 first
=> fix: open API link reference proxy design pattern implementation

src/Microsoft.OpenApi/Models/Interfaces/IOpenApiParameter.cs, src/Microsoft.OpenApi/Models/References/BaseOpenApiReferenceHolder.cs, src/Microsoft.OpenApi/Models/References/OpenApiCallbackReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiExampleReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiHeaderReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiLinkReference.cs, src/Microsoft.OpenApi/Models/References/OpenApiParameterReference.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
partial #1998, review #2093 first
=> chore: refactors common reference work to a base class to reduce duplication

src/Microsoft.OpenApi/Models/OpenApiSchema.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.SerializeReferencedSchemaAsV3JsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.SerializeReferencedSchemaAsV3JsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.SerializeReferencedSchemaAsV3WithoutReferenceJsonWorksAsync_produceTerseOutput=False.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.SerializeReferencedSchemaAsV3WithoutReferenceJsonWorksAsync_produceTerseOutput=True.verified.txt, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs
null type in the object model now results in nullable true for 3.0 serialization
=> fix: a bug where 3.0 downcast of type null would not work

test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterAnyExtensionsTests.cs
On a system configured for german language the tests weren't working because the . on the german system are written as , which results in invalid json, because the StreamWriter depends on the CurrentCulture by default.
=> Remove dependency on CurrentCulture in tests

src/Microsoft.OpenApi.Readers/OpenApiYamlReader.cs, src/Microsoft.OpenApi/Reader/OpenApiJsonReader.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> fix: removes unused parameters

src/Microsoft.OpenApi.Hidi/OpenApiService.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, src/Microsoft.OpenApi/Reader/OpenApiModelFactory.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs
Fixes #1989 where the document's format was not being correctly set for non-standard MIME types when inspecting the content type header in a HTTP response object.
E.g. the MIME type `text/x-yaml` which is still in use by older libraries or APIs
=> fix: support non-standard MIME type in response header

src/Microsoft.OpenApi/Reader/V3/OpenApiV3Deserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiV31Deserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiCompoentsTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiSchema/externalReferencesSchema.yaml
A reference like ./Directory/File.json#/components/schema/abc was before read as:
refId = abc
externalResource = ./Directory
Which dropped the file name, which will be fixed by this commit
This fix will help the issue https://github.com/microsoft/OpenAPI.NET/issues/1674 to get fixed.
=> Fix: reference with folder loading

src/Microsoft.OpenApi.Workbench/MainModel.cs, src/Microsoft.OpenApi/Reader/OpenApiReaderSettings.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Remove unused ReferenceResolution parameter from OpenApiReaderSettings

src/Microsoft.OpenApi/Models/Interfaces/IOpenApiSchema.cs, src/Microsoft.OpenApi/Models/OpenApiConstants.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs, src/Microsoft.OpenApi/Reader/ParseNodes/MapNode.cs, src/Microsoft.OpenApi/Reader/ParseNodes/ParseNode.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterExtensions.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiDocument/documentWithReusablePaths.yaml, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiDocument/documentWithWebhooks.yaml, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiSchema/jsonSchema.json, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
- feat: add support for dependentRequired
- doc: update Public API
- chore: remove unused function
Fixes #2123
=>  feat: add support for dependentRequired

src/Microsoft.OpenApi/Extensions/OpenApiTypeMapper.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Validations/Rules/RuleHelpers.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
- Adds support for normalizing flaggable enums by returning an array of strings
- Supports casting of type arrays to the flaggable enum type
- Adds tests to validate
Fixes #2078
Fixes #1924
=> fix: refactor ToIdentifier() to normalize flaggable enums

src/Microsoft.OpenApi/Models/Interfaces/IOpenApiSchema.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs, src/Microsoft.OpenApi/Reader/V2/OpenApiHeaderDeserializer.cs, src/Microsoft.OpenApi/Reader/V2/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Reader/V3/OpenApiSchemaDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiSchemaDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> fix: deduplicates exclusive min/max properties in the object model

src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Reader/V2/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi/Reader/V3/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiDocumentDeserializer.cs, src/Microsoft.OpenApi/Services/OpenApiFilterService.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> Rename `OpenApiDocument.SecurityRequirements` as `Security`. Fixes #2155

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj, src/Microsoft.OpenApi/Microsoft.OpenApi.csproj, src/Microsoft.OpenApi/Models/References/BaseOpenApiReferenceHolder.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiFilterServiceTests.cs, test/Microsoft.OpenApi.Hidi.Tests/UtilityFiles/docWithReusableHeadersAndExamples.yaml, test/Microsoft.OpenApi.Tests/Models/References/OpenApiTagReferenceTest.cs
fix: fixes serialization of openApidocs with operation tags with settings to inline references
Fixes #https://github.com/microsoft/OpenAPI.NET/issues/2233
=> fix: fixes serialization of openApidocs with operation tags with settings to inline references

src/Microsoft.OpenApi/Interfaces/IMetadataContainer.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
=> chore: rename annotations to metadata

src/Microsoft.OpenApi/Models/Interfaces/IOpenApiSchema.cs, src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
IOpenApiSchema interface already contains a UnevaluatedProperties property (different case).
=> Remove duplicate property UnEvaluatedProperties 

.azure-pipelines/ci-build.yml, Microsoft.OpenApi.sln, src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj
Reverts the previous change to exclude hidi in the solution file and CI in order to fix ambiguity in package source mapping references.
=> fix: Include hidi in solution

src/Microsoft.OpenApi/Models/OpenApiComponents.cs, test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/Samples/docWithSecurityScheme.yaml
This PR fixes a bug where the security schemes object within the components wasn't being serialized when `InlineLocalReferences` or `InlineExternlRefeences` is enabled.
Fixes #2267
=> fix: always serialize security schemes in components

src/Microsoft.OpenApi/Reader/V2/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi/Reader/V3/OpenApiOperationDeserializer.cs, src/Microsoft.OpenApi/Reader/V31/OpenApiOperationDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiDocument/documentWithEmptyTags.json
When parsing the list of tags, removed tags that are empty so we don't fail on them.
=> Fix issue Empty tag causes error generating Kiota client #2283

src/Microsoft.OpenApi/Attributes/TrimmingAttributes.cs, src/Microsoft.OpenApi/Extensions/OpenApiTypeMapper.cs, src/Microsoft.OpenApi/Models/OpenApiComponents.cs, src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/OpenApiMediaType.cs, src/Microsoft.OpenApi/Models/OpenApiOperation.cs, src/Microsoft.OpenApi/Models/OpenApiReference.cs, src/Microsoft.OpenApi/OpenApiTagComparer.cs, src/Microsoft.OpenApi/Services/OpenApiWalker.cs, src/Microsoft.OpenApi/Services/OpenApiWorkspace.cs, src/Microsoft.OpenApi/Writers/OpenApiWriterExtensions.cs
=> chore: cleans up nullable directives

src/Microsoft.OpenApi/Reader/V2/OpenApiParameterDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiParameterTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/Samples/OpenApiParameter/formDataParameter.json
=> fix: set format to binary for file uploads

src/Microsoft.OpenApi/Interfaces/IMetadataContainer.cs, src/Microsoft.OpenApi/Models/Interfaces/IOpenApiSchema.cs, src/Microsoft.OpenApi/Models/OpenApiSchema.cs, src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs, test/Microsoft.OpenApi.Readers.Tests/OpenApiWorkspaceTests/OpenApiWorkspaceStreamTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
while updating #2298 I noticed we had misalignment here
=> fix: renames annotations schema property to metadata to match #2241

src/Microsoft.OpenApi/Models/OpenApiDocument.cs
Use `Convert.ToHexString()` when targeting .NET 8 instead of using a `StringBuilder`.
=> Use Convert.ToHexString

src/Microsoft.OpenApi/Models/OpenApiDocument.cs
Use `SHA512.HashDataAsync()` for .NET 8 to reduce allocations.
Complements the change in #2322.
I manually verified the hash before and after was the same by getting the hash from the `TestHashCodesForSimilarOpenApiDocuments` test using the debugger and then verifying it was the same after the change with:
```csharp
Assert.Equal("00BCB7FE78379A07956E06BF3180A8818F6E42E10BC38A7012A342CD6E1033BF03CB7E70E04B285C67BF4D78828D185C1FE438073C2474E40315F2ECE6310B78", doc1HashCode);
```
=> Use SHA512.HashDataAsync

src/Microsoft.OpenApi/Models/OpenApiOperation.cs, src/Microsoft.OpenApi/Models/References/OpenApiTagReference.cs, src/Microsoft.OpenApi/OpenApiTagComparer.cs, test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiFilterServiceTests.cs, test/Microsoft.OpenApi.Hidi.Tests/UtilityFiles/docWithReusableHeadersAndExamples.yaml, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentTests.ParseDocumentWith31PropertiesWorks.verified.txt, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiDocument/documentWith31Properties.yaml, test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs, test/Microsoft.OpenApi.Tests/OpenApiTagComparerTests.cs
- Update `OpenApiTagComparer` to behave intuitively with `OpenApiTagReference` instances pointing to tags not defined in an `OpenApiDocument`.
- Verify OpenAPI tag references refer to a valid OpenAPI tag in the document on serialization.
Fixes #2319.
=> fix: Improve handling of OpenAPI tag references

test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentSerializationTests .cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiDocument/docWith31properties.json
Adds a unit test to inspect whether we mutate any public properties in the DOM by:
- Adding a complete OpenApi document - with 3.1 features and loading it into a DOM
- Serializing the DOM using a standard serializer - System.Text.JSON
- Serializing the same DOM using our current serialization infrastructure
- Serializing the DOM again using STJ
- Doing a deep comparison for the two STJ-serialized versions. If they're different, our custom serialization likely mutated the public DOM.
Fixes #2080
=> chore: inspect for mutations in serialization methods

src/Microsoft.OpenApi/Reader/OpenApiModelFactory.cs, src/Microsoft.OpenApi/Services/OpenApiWorkspace.cs, test/Microsoft.OpenApi.Readers.Tests/OpenApiWorkspaceTests/OpenApiWorkspaceStreamTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Tests/Reader/OpenApiModelFactoryTests.cs
follow up to #2243
CC @dldl-cmd
=> fix: base url should be read from the settings when available

docs/upgrade-guide-2.md
Wrap references to code members in backticks and clarify some terminology.
=> docs: Improve upgrade guide formatting

src/Microsoft.OpenApi/Models/Interfaces/IOpenApiSchema.cs
=> fix: wrong link to json schema spec in schema doc comments

src/Microsoft.OpenApi/Services/OpenApiUrlTreeNode.cs, test/Microsoft.OpenApi.Tests/Services/OpenApiUrlTreeNodeTests.cs
=> fix: tree node has the wrong structure because of trailing slashes

src/Microsoft.OpenApi/Models/BaseOpenApiReference.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/ReferenceSamples/relativeSubschemaReference.json, test/Microsoft.OpenApi.Readers.Tests/V31Tests/RelativeReferenceTests.cs
=> fix: a bug where relative relative and sub-component JSON references would not resolve properly

src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Services/OpenApiWorkspace.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/RelativeReferenceTests.cs
=> fix: relative uri in json schema references would not parse appropriately or provide feedback to the user

src/Microsoft.OpenApi/Models/OpenApiDocument.cs, src/Microsoft.OpenApi/Models/References/BaseOpenApiReferenceHolder.cs, src/Microsoft.OpenApi/Services/OpenApiWorkspace.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/RelativeReferenceTests.cs
- **chore: adds additional multiple levels of references test cases**
- **chore: adds update to parent property**
- **fix: avoid stack overflow on cyclical references**
=> avoid stack overflow on cyclical references

README.md, release-please-config.json
=> docs: adds an insert about versioning issues for the preview

docs/upgrade-guide-2.md
Contributes to #2442
- Fixes title of document, was `Upgrade guide to OpenAPI.NET 2.1 ` before
- Fixes [MD059](https://github.com/DavidAnson/markdownlint/blob/v0.38.0/doc/md059.md) helpful link text
- Remove trailing and unnecessary white space
- Typo correction of British English `behaviour` to American English `behavior`
- Fix basic markdown lint issues
Ideally there should be some type of markdown lint that runs on CI and a typo checker (added benefit would avoid typo squatting issues as seen in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5278)
I get a markdownlint warning MD025/single-title/single-h1: Multiple top-level headings in the same document for the `# Introduction` header since front matter is being used but I left it as is.
=> Add warning for ASP.NET Core version `< 10.0`

src/Microsoft.OpenApi/Properties/SRResource.Designer.cs, src/Microsoft.OpenApi/Properties/SRResource.resx, src/Microsoft.OpenApi/Validations/Rules/OpenApiDocumentRules.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Validations/OpenApiDocumentValidationTests.cs, test/Microsoft.OpenApi.Tests/Validations/ValidationRuleSetTests.cs
Add validation rule for OpenAPI document schema references.
Resolves #2453.
---
~~Initial draft for now based on testing this approach with https://github.com/dotnet/aspnetcore/pull/63095. Needs tests, plus rebasing after #2460 is merged.~~
=> Validate OpenAPI schema references

src/Microsoft.OpenApi/Services/OpenApiVisitorBase.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiContactRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiDocumentRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiExtensionRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiExternalDocsRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiInfoRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiLicenseRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiNonDefaultRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiOAuthFlowRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiParameterRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiPathsRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiRecommendedRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiResponseRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiResponsesRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiSchemaRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiServerRules.cs, src/Microsoft.OpenApi/Validations/Rules/OpenApiTagRules.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Validations/OpenApiRecommendedRulesTests.cs
- Add new `OpenApiRecommendedRules` class that adds a new `GetOperationShouldNotHaveRequestBody` rule.
- Avoid using `Enter()` and `Exit()` operations in validation rules where possible to avoid stack push/pop calls these perform.
- Use `string` not `String`.
- Remove redundant comments.
- Fix typo in comment.
Resolves #2454.
=> Add Validation Rule for path operations to not have a request body

src/Microsoft.OpenApi.YamlReader/OpenApiYamlReader.cs, src/Microsoft.OpenApi/Reader/OpenApiDiagnostic.cs, src/Microsoft.OpenApi/Reader/OpenApiJsonReader.cs, src/Microsoft.OpenApi/Reader/ReadResult.cs, test/Microsoft.OpenApi.Readers.Tests/OpenApiReaderTests/OpenApiStreamReaderTests.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiServerTests.cs, test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiCallbackTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs, test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiSchemaTests.cs, test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt, test/Microsoft.OpenApi.Tests/Reader/OpenApiModelFactoryTests.cs
This pull request is adding the format to the diagnostics.
This is helpful as the library does auto-detection of the format of the document. So any tool using the library to arbitrarily open a json/yaml document, apply a couple of changes, and serialize back, can now maintain the output format.
=> feat: adds the detected format as part of the diagnostics

src/Microsoft.OpenApi.Hidi/readme.md
The examples show a wrong value for specifying the OpenApi version. Using the examples I got this error:
> crit: Microsoft.OpenApi.Hidi.Handlers.TransformCommandHandler[0]
Could not transform the document, reason: Invalid version format. Please provide a valid OpenAPI version (e.g., 2.0, 3.0, 3.1).
PS Z:\Sources\dotnet10\ai> hidi transform -d .\openapi.yaml -f yaml -o .\openapi-trimmed.yaml -v OpenApi3_0 --op users.user.calendar.getSchedule,places.place.ListPlace.AsRoom --co
It took me a while before I figured out I need to use the major minor syntax, so `-v OpenApi3_0` must be changed to `-v 3.0` to get the examples working.
=> Fix wrong version specification in hidi examples in readme.md

src/Microsoft.OpenApi/Models/OpenApiEncoding.cs, test/Microsoft.OpenApi.Tests/Models/OpenApiEncodingTests.cs
Fix: Explode serialization is wrong when style is "form"
This fixes the same problem as https://github.com/microsoft/OpenAPI.NET/pull/544 but for OpenApiEncoding.
The spec describes different behavior depending on if it is set or not (see: https://spec.openapis.org/oas/v3.1.0.html#fixed-fields-12) and also different defaults depending on the style value.
Cherry pick for https://github.com/microsoft/OpenAPI.NET/pull/2508 to the main branch
I don't have dotnet 10 installed yet so I hope this works without it.
=> Fix OpenApiEncoding explode property serialization (to main)

src/Microsoft.OpenApi/Reader/V2/OpenApiDocumentDeserializer.cs, test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiServerTests.cs
Updated the `MakeServers` method to include checks for `defaultUrl` and refined host validation. Modified the `BuildUrl` method to correctly extract ports and remove default ports from URLs. Added unit tests in `OpenApiServerTests.cs` to ensure proper handling of base URLs and ports across various scenarios.
fixes #1294
=> Improve server creation and URL handling logic-V2

.github/workflows/release-please-gha.yml
The auto-release detection on support/v1 has not been working as expected forcing me to create those releases manually.
https://github.com/microsoft/OpenAPI.NET/actions/runs/18290786080/job/52077236107
This is time consuming, and not my primary responsibility.
This PR aims to dynamically set the target branch based off the trigger to patch for the failing automatic branch detection
=> ci: fixes target branch definition to support multiple releases automatically
