microsoft/OpenAPI.NET

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

update the version to 009

---

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj
test/Microsoft.OpenApi.Readers.Tests/ReferenceService/TryLoadReferenceV2Tests.cs
test/Microsoft.OpenApi.Readers.Tests/Resources.cs
test/Microsoft.OpenApi.Readers.Tests/V2Tests/ComparisonTests.cs
test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiParameterTests.cs
test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiSecuritySchemeTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiCallbackTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDiscriminatorTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiEncodingTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiExampleTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiInfoTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiSchemaTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiSecuritySchemeTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiXmlTests.cs

See #156 
Embedded the test files into the test project and make the test self-contain.

Embedded the test files into project and make test self-contain

---

src/Microsoft.OpenApi.Workbench/MainModel.cs
src/Microsoft.OpenApi.Workbench/MainWindow.xaml

- Add missing scrollbar
- Update versions to V3.0.1 and V2.0 for accuracy

Small appearance fixes in Workbench

---

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

PR to change nuget version for new release

Updated to v1.0.0-beta015

---

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Updated version to enable pushing a new Nuget package for this preview.

Updated nuget version to 1.1.preview.2

---

src/Microsoft.OpenApi/Models/OpenApiOperation.cs

Added empty schema to body parameters in V2 when no schema

---

src/Microsoft.OpenApi.Readers/V2/OpenApiV2VersionService.cs
src/Microsoft.OpenApi/Models/OpenApiDocument.cs
test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs

Fixed thrown exceptions 

---

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Going to do this final preview release and then merge vnext into master to release 1.1

Updated to nuget package to v1.1-preview.4

---

src/Microsoft.OpenApi.Readers/Exceptions/OpenApiUnsupportedSpecVersionException.cs

Changed exception to not be reported as error but thrown

---

src/Microsoft.OpenApi.Readers/V3/OpenApiMediaTypeDeserializer.cs

fixes #308. it would be great to get this in v1.1. 
aside: when is v1.1 due out?

enabling encoding; refactor to use constants

---

src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs
test/Microsoft.OpenApi.Tests/Writers/OpenApiJsonWriterTests.cs
test/Microsoft.OpenApi.Tests/Writers/OpenApiWriterAnyExtensionsTests.cs
test/Microsoft.OpenApi.Tests/Writers/OpenApiYamlWriterTests.cs

vNext merge of #322 

---

src/Microsoft.OpenApi.Readers/ParseNodes/ValueNode.cs
test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiDocumentTests.cs

A couple of places where CultureInfo.InvariantCulture was not added.
A second fix of #323 in addition to #326 .

Add CultureInfo.InvariantCulture in the TryParse's in CreateAny.

---

src/Microsoft.OpenApi.Readers/Services/OpenApiReferenceResolver.cs

Merging changes from @senthilkumarmohan in #339 into master branch since it's a bug fix.

fixes#330-Yield validation err when an invalid security req key found

---

src/Microsoft.OpenApi.Readers/V2/OpenApiDocumentDeserializer.cs
test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiServerTests.cs

fixes#319 - V2Deserializer should handle invalid host value gracefully

---

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Include the following PR changes:
Bugfix#344 report error when one of schema doesnt have the discriminator property bug-fix
#346 by senthilkumarmohan was merged 27 days ago • Approved  
Parsing IOpenApiAny should respect format and type  bug-fix
#343 by PerthCharern was merged on Nov 7 • Approved  
Add more tests for examples in Media Type 
#342 by PerthCharern was merged 27 days ago • Approved  
fixes#330-Yield validation err when an invalid security req key found  bug-fix
#341 by PerthCharern was merged on Oct 30 • Approved  
fixes#319 - V2Deserializer should handle invalid host value gracefully  bug-fix
#340 by senthilkumarmohan was merged on Oct 31 • Approved

Release 1.1.2

---

README.md

Came across this repo but no link to nuget, had to search nuget to find it. This provides a direct link

Add nuget badge to link users to

---

build.cmd
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Package Version in csproj files has been updated to 1.2.0-preview.   1.2.0 milestone issues will be merged into master and released as a preview.

Updated nuget versions for next package release

---

src/Microsoft.OpenApi.Readers/Services/OpenApiReferenceResolver.cs

Resolve all references in a parameter object

---

src/Microsoft.OpenApi/Models/OpenApiParameter.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs

Added new unit tests that demonstrate the problem and assert the fix.

Fixes #456.

---

src/Microsoft.OpenApi.Readers/ParseNodes/OpenApiAnyConverter.cs

The problem with previous implementation is that explicit strings are parsed as date-time even if format is not specified. This new implementation tries to guess type of value from a more narrow set of types for explicit strings.

Safer parsing of explicit strings

---

build.cmd
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi.Readers/OpenApiTextReaderReader.cs
src/Microsoft.OpenApi/Any/OpenApiString.cs
src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
src/Microsoft.OpenApi/Writers/OpenApiJsonWriter.cs
src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs
src/Microsoft.OpenApi/Writers/OpenApiYamlWriter.cs

This PR includes changes made to the 1.2 release in master.

Update vnext from master

---

src/Microsoft.OpenApi/Services/OpenApiWalker.cs

Fixes to OpenApiWalker 

---

src/Microsoft.OpenApi.Readers/Services/OpenApiReferenceResolver.cs
test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiResponseTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiResponse/responseWithHeaderReference.yaml

Resolve header references on read

---

src/Microsoft.OpenApi/Services/OpenApiExampleComparer.cs
src/Microsoft.OpenApi/Services/OpenApiParameterComparer.cs
src/Microsoft.OpenApi/Services/OpenApiRequestBodyComparer.cs
src/Microsoft.OpenApi/Services/OpenApiSchemaComparer.cs
src/Microsoft.OpenApi/Services/OpenApiSecuritySchemeComparer.cs
test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
test/Microsoft.OpenApi.Tests/Services/OpenApiComparerTestCases.cs
test/Microsoft.OpenApi.Tests/Services/OpenApiComparerTests.cs
test/Microsoft.OpenApi.Tests/Services/OpenApiEncodingComparerTests.cs
test/Microsoft.OpenApi.Tests/Services/OpenApiInfoComparerTests.cs
test/Microsoft.OpenApi.Tests/Services/OpenApiSecuritySchemeComparerTests.cs
test/Microsoft.OpenApi.Tests/Services/OpenApiServersComparerTests.cs
test/Microsoft.OpenApi.Tests/Services/OpenApiTagComparerTests.cs

Modified IOpenApiReferenceable comparers to handle self-referencing references.
Corrected typo in OpenApiSecuritySchemeComparer parameters.

Fix stack overflow

---

.vscode/launch.json

This code was removed from the 1.3 release until we decide which implementation of comparer we are moving forward with.

Original OpenAPI Comparer implementation

---

build.cmd
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi.Tool/Microsoft.OpenApi.Tool.csproj
src/Microsoft.OpenApi.Tool/OpenApiService.cs
src/Microsoft.OpenApi.Tool/Program.cs
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Updated version and added extenalReference support to commandline tool

---

src/Microsoft.OpenApi/Models/OpenApiSchema.cs

Added support for serializing additional properties in v2 schema

---

src/Microsoft.OpenApi.Readers/V2/OpenApiExternalDocsDeserializer.cs
src/Microsoft.OpenApi.Readers/V3/OpenApiExternalDocsDeserializer.cs

Added support for parsing extensions in externaldocs

---

.github/workflows/codeql-analysis.yml

Adds a push trigger filter in our main branch for the codeql analysis step

Add a push trigger filter during CodeQL analysis

---

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Updating to 1.3.1-preview as a mistake.  I should have updated to 1.3.0-preview2.  The next update will be to 1.3.1-preview2

Update package version numbers

---

src/Microsoft.OpenApi/Validations/Rules/OpenApiParameterRules.cs

Fixed validate for Path Parameters so it does not fail for components

---

.vscode/launch.json
.vscode/tasks.json
src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Hidi/OpenApiService.cs

- - fixes an issue where hidi would not process async
- - updates vs code configuration files to be able to debug hidi

fixes an issue where hidi would not process async

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

- bumps hidi version

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Hidi/OpenApiService.cs

related to https://github.com/microsoftgraph/msgraph-sdk-go/issues/161

enables discriminator in hidi

---

.github/workflows/docker.yml

headS not head 🤦

---

.github/CODEOWNERS

- adds code owner configuration to the repository

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Updates csproj release notes to point to Github release notes

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

- bumps hidi version and reference to conversion lib

---

src/Directory.Build.props
src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

since it is already in dir props. also update the ref in props to be stable

remove duplicate SourceLink

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

This PR creates the `1.0.0-preview9` release for Hidi

Hidi release

---

src/Microsoft.OpenApi/Attributes/DisplayAttribute.cs
test/Microsoft.OpenApi.Tests/Attributes/DisplayAttributeTests.cs
test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt

Resolve #889 
Changes:
`DisplayAttribute`  from internal to public
Updated [PublicApi.approved.txt](https://github.com/microsoft/OpenAPI.NET/compare/vnext...fernandolamp:enhancement/fgd/changeDisplayAttributeToPublic?expand=1#diff-8a7cb10fa55a8c4f5acd871bda7e4418f07214eccd4119db2ee06e6379f56f9f)
Created some tests

feat: change DisplayAttribute to public

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Helps to unify and make feature requests and bug reports more concise to eliminate back and forths.
Fixes #971

Adds an issue and feature template

---

src/Microsoft.OpenApi/Models/OpenApiOperation.cs

Cater for file content transferred with base64 encoding

---

src/Microsoft.OpenApi/Models/OpenApiSchema.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs

Patch fix to @MaggieKimani1 branch

Retrieve Format property when serializing as V2

---

.github/workflows/docker.yml

related https://github.com/microsoft/mcr/pull/2234

- renames hidi in accordance to naming policy of MCR

---

src/Microsoft.OpenApi/Models/OpenApiSchema.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs

StackOverflow when using OpenApiSchema Copy Constructor

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

- bumps hidi version to get latest odata and mermaid

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Hidi/Program.cs

Return correct exit code on validation error

---

src/Microsoft.OpenApi.Readers/OpenApiYamlDocumentReader.cs
src/Microsoft.OpenApi/Validations/ValidationRuleSet.cs
test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt
test/Microsoft.OpenApi.Tests/Validations/ValidationRuleSetTests.cs

Update ValidationRuleSet.Rules to be an IEnumerable collection not IList

---

src/Microsoft.OpenApi/Models/OpenApiSchema.cs

Missed settings.LoopDetector.PopLoop<OpenApiSchema> in SerializeAsV2

Fix loop detector OpenApiSchema.

---

src/Microsoft.OpenApi/Models/OpenApiParameter.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.SerializeAdvancedDocumentAsV3JsonWorks_produceTerseOutput=False.verified.txt
test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.SerializeAdvancedDocumentWithReferenceAsV3JsonWorks_produceTerseOutput=False.verified.txt
test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.SerializeDuplicateExtensionsAsV3JsonWorks_produceTerseOutput=False.verified.txt
test/Microsoft.OpenApi.Tests/Models/OpenApiOperationTests.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.SerializeReferencedParameterAsV3JsonWithoutReferenceWorksAsync_produceTerseOutput=False.verified.txt
test/Microsoft.OpenApi.Tests/Models/OpenApiParameterTests.cs
test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt

Fixes parameter style property getter that changes model data

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

Bumps conversion lib and hidi version for next weeks release

Bump hidi version

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

- fixes readme path to the correct hidi readme

---

.azure-pipelines/ci-build.yml
src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

- fixes an issue where executable release would fail because of warn as error

---

README.md
src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

Bump lib versions

---

Directory.Build.props
src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
test/Microsoft.OpenApi.Hidi.Tests/Microsoft.OpenApi.Hidi.Tests.csproj
test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj
test/Microsoft.OpenApi.SmokeTests/Microsoft.OpenApi.SmokeTests.csproj
test/Microsoft.OpenApi.Tests/Microsoft.OpenApi.Tests.csproj

see commit message for changes

Cleanup csproj

---

src/Microsoft.OpenApi/Validations/ValidationRuleSet.cs

before: 3 dictionary lookups
after: 1 dictionary lookup

remove duplicate dictionary lookups in ValidationRuleSet.Add

---

src/Microsoft.OpenApi/Models/OpenApiLink.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiLinkTests.cs

Fix link extensions serialization

---

src/Microsoft.OpenApi/Services/OpenApiWalker.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiSchemaTests.cs

Visit OpenApiSchema.Not property in OpenApiWalker

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

Bumps Hidi to get access to new preview version of conversion lib.

Bumps Hidi version

---

src/Microsoft.OpenApi/Services/OpenApiWalker.cs
test/Microsoft.OpenApi.Tests/Walkers/WalkerLocationTests.cs

Fix unresolved references in OpenApiWalker

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

Updates Microsoft.OpenApi.OData from `1.5.0` to `1.6.0-preview.2`

Bumps up conversion lib.

---

.github/workflows/ci-cd.yml
.github/workflows/sonarcloud.yml

more information https://docs.opensource.microsoft.com/github/apps/permission-changes/

 - adds permissions to workflows

---

.github/workflows/codeql-analysis.yml

Related to: https://github.com/microsoft/OpenAPI.NET/pull/1549#issuecomment-1928112504

Adds missing codeql permissions

---

src/Microsoft.OpenApi.Hidi/readme.md

correct the CSDL to OpenAPI conversion example to use '--csdl' instead of '--input'

Update Hidi readme.md

---

src/Microsoft.OpenApi/Reader/OpenApiReaderRegistry.cs

Fixes concurrent error with registry

---

src/Microsoft.OpenApi/Models/OpenApiReference.cs
src/Microsoft.OpenApi/Reader/V3/OpenApiV3VersionService.cs
test/Microsoft.OpenApi.Tests/PublicApi/PublicApi.approved.txt

Fixes Fragment typo

---

.azure-pipelines/ci-build.yml

Update pipeline to be 1ES compliant

---

.github/CODEOWNERS

Swaps Carlos with Gavin as code reviewers

Update code reviewers

---

src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj

Related to: https://github.com/microsoft/OpenAPI.NET/pull/1754

Remove packages potentially causing build to fail in AzDo pipeline

---

src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj
src/Microsoft.OpenApi/Models/OpenApiMediaType.cs
test/Microsoft.OpenApi.Tests/Models/OpenApiDocumentTests.cs

Fix examples serialization causing NullReferenceException

---

test/Microsoft.OpenApi.Hidi.Tests/Services/OpenApiFilterServiceTests.cs
test/Microsoft.OpenApi.Hidi.Tests/UtilityFiles/docWithReusableHeadersAndExamples.yaml

Investigate: Check whether server info changes during slicing

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi.Workbench/Microsoft.OpenApi.Workbench.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

fix: uses the correct threading dependency to avoid impacting downstream projects

---

src/Microsoft.OpenApi/Services/OpenApiUrlTreeNode.cs
test/Microsoft.OpenApi.Tests/Services/OpenApiUrlTreeNodeTests.cs

Continuation of #1584, specifically addresses [these comments](https://github.com/microsoft/OpenAPI.NET/pull/1584#pullrequestreview-1946753601)
Fixes #1580

Support trailing slashes in paths

---

src/Microsoft.OpenApi/Models/References/OpenApiCallbackReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiExampleReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiHeaderReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiLinkReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiParameterReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiPathItemReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiRequestBodyReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiResponseReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiSecuritySchemeReference.cs
src/Microsoft.OpenApi/Models/References/OpenApiTagReference.cs

Simplify null/empty string checks 

---

src/Microsoft.OpenApi/Extensions/OpenApiTypeMapper.cs

docs: fixes doc comments to align with changes made in #1883

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
test/Microsoft.OpenApi.Readers.Tests/Microsoft.OpenApi.Readers.Tests.csproj
test/Microsoft.OpenApi.Readers.Tests/OpenApiReaderTests/OpenApiStreamReaderTests.cs

fixes security issues for v1 branch
context https://github.com/microsoft/OpenAPI.NET/actions/runs/12415296753/job/34661341249

security: bumps STJ version to fix security vulnerabilities

---

.azure-pipelines/ci-build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docker.yml

ci: updates main with the latest ci changes

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

wait for #2012 to be merged first

chore: bumps version for releasing

---

.azure-pipelines/ci-build.yml

fix: reverts to a regular variable for the tag value

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
src/Microsoft.OpenApi.Readers/Microsoft.OpenApi.Readers.csproj
src/Microsoft.OpenApi/Microsoft.OpenApi.csproj

waiting on
- #2023 
- #2024
- #2026

chore: bumps preview version

---

src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj

Signed-off-by: GitHub <noreply@github.com>

chore: releases hidi and aligns on 1.X

---

src/Microsoft.OpenApi/MicrosoftExtensions/OpenApiEnumValuesDescriptionExtension.cs

fix: conditional version for extension causes invalid json

---

src/Microsoft.OpenApi/Models/OpenApiSchema.cs
src/Microsoft.OpenApi/Models/References/OpenApiSchemaReference.cs
test/Microsoft.OpenApi.Readers.Tests/V2Tests/OpenApiSchemaTests.cs

still needs an additional unit test to prevent future regressions

fix: v2 references for properties do not work as expected

---

src/Microsoft.OpenApi/Reader/V3/OpenApiRequestBodyDeserializer.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/OpenApiDocumentTests.cs
test/Microsoft.OpenApi.Readers.Tests/V3Tests/Samples/OpenApiDocument/docWithExampleReferences.yaml

Fix: Error validating OpenAPI using hidi preview

---

src/Microsoft.OpenApi/Models/OpenApiReference.cs

fix: do not copy host document as it negatively impact performance

---

.github/policies/resourceManagement.yml

adds an issue automation configuration to automate stale issues closure

ci: adds issues automation configuration

---

test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiComponentsTests.cs
test/Microsoft.OpenApi.Readers.Tests/V31Tests/OpenApiDocumentTests.cs
test/Microsoft.OpenApi.Readers.Tests/V31Tests/Samples/OpenApiDocument/docWithReferencedExampleInSchemaWorks.yaml

chore: no validation warnings from examples with date-time format

---

.github/CODEOWNERS

security: aligns code owners with security team

---

.azure-pipelines/ci-build.yml

ci: fix image tag when publishing from git tag

---

.github/workflows/release-please-gha.yml

ci: adds release please wf to support vi branch

---

.github/workflows/release-please-gha.yml

ci: fixes target branch detection support for release please
